[NWS-1169][NWS-1244] Criar serviço de movimentação interna
ninc-management/plataforma pull request #173
Opened 2022-05-03 22:26 UTC by augustoicaro

2022-05-03 23:36 UTC, WilamisAviz15 approved these changes

2022-05-03 23:37 UTC, leo-holanda requested changes

2022-05-03 23:37 UTC, leo-holanda commented on src/app/shared/services/internalTransaction.service.ts
> +          });
Aqui daria pra usar a função reviveDates do utils?

2022-05-03 23:37 UTC, leo-holanda commented on src/app/shared/services/internalTransaction.service.spec.ts
> +    tmpTransaction.description = 'Redestribuição mensal para os caixas dos times';
Typo

2022-05-03 23:37 UTC, leo-holanda commented on src/app/shared/services/internalTransaction.service.spec.ts
> +    tmpTransaction.description = 'Distruibuição de libro trimestral 1/4';
Typo

2022-05-03 23:37 UTC, leo-holanda commented on src/app/shared/services/internalTransaction.service.spec.ts
> +    tmpTransaction.description = 'Aporte do resto do tinheiro do contrato no time';
Typo

2022-05-04 02:45 UTC, augustoicaro commented on src/app/shared/services/internalTransaction.service.ts
> +          });
Dá sim, mas só entrou para o `main` agora. Bem apontado, vou fazer o rebase e alterar

2022-05-05 23:42 UTC, leo-holanda approved these changes

2022-05-10 23:44 UTC, merged