[NWS-1321][NWS-1363] Handle control access list in contact with dynam…
ninc-management/plataforma pull request #176
Opened 2022-05-05 22:51 UTC by Elygledson

…ic role list

2022-05-05 22:57 UTC, Elygledson commented
![2022-05-05 (1)](https://user-images.githubusercontent.com/47836992/167039776-b4bfcd90-5fc7-469a-97eb-53f0ad8d0fa1.png)
![2022-05-05](https://user-images.githubusercontent.com/47836992/167039786-8b9deb7b-bb95-4b46-bf8f-8134aae28c8e.png)

2022-05-06 18:17 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +  userService: any;
Esse userService é usado em algum lugar? Não consegui ver e achei estranho estar com o tipo any

2022-05-06 18:20 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
>                    name="roleType"
Vi que já estava assim mas acho que seria uma boa trocar o jeito de escrita da propriedade name do input de cammelCase pro kebab-case pra manter a consistência com outras partes do código

2022-05-06 18:22 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +                  name="permissionType"
Mesma coisa do outro comentário do kebab-case

2022-05-06 18:23 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newLevel?.length == 0"
Mesma coisa do outro comentário do booleano

2022-05-06 18:26 UTC, leo-holanda commented on src/app/shared/guards/auth.guard.ts
> +              };
Achei estranho essa parte. Independente da condição o objeto recebe o mesmo valor. É essa a intenção mesmo? Porque aí não precisaria checar as condições

2022-05-06 23:00 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  userService: any;
Não, removi aqui

2022-05-06 23:05 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +                  name="permissionType"
eu fiz assim porque nas despesas ele faz assim também. Agora estou na dúvida. Mas eu troquei o da propriedade

2022-05-06 23:09 UTC, Elygledson commented on src/app/shared/guards/auth.guard.ts
> +              };
Por enquanto sim

2022-05-07 00:39 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +                  name="permissionType"
Verdade kkkkk me confundi

2022-05-09 12:40 UTC, Elygledson commented on backend/src/models/platformConfig.ts
> +export class AcessControl {
Feito aqui.

2022-05-09 12:41 UTC, Elygledson commented on backend/src/models/platformConfig.ts
> +  typeName: string = '';
hum talvez seja mesmo.

2022-05-09 12:42 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newRole.typeName?.length !== 0 && newRole.permission?.length !== 0 ? false : true"
Estou na dúvida sobre isso porque estranhamente funciona em outras lugares dessa segunda maneira. Mas vou ver esse ponto aqui. Bem lembrado!

2022-05-09 19:44 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei e os comentários nos pontos do Leo

2022-05-09 19:44 UTC, augustoicaro commented on backend/src/models/platformConfig.ts
> +  typeName: string = '';
Fica melhor mesmo

2022-05-09 19:44 UTC, augustoicaro commented on playground.mongodb
> +});
Não precisamos dessa função no playground, porque o config ainda não está em produção. Temos que fazer na a alteração no banco, mas não precisa ser salvo no repositório

2022-05-09 19:44 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newRole.typeName?.length !== 0 && newRole.permission?.length !== 0 ? false : true"
Também isso aqui está mal escrito, estamos convertendo boleano em boleano. Já falamos disso algumas vez, precisa ter mais atenção nessa parte. O jeito mais adequado seria algum desses:

* Com referência local:
```ts
 [disabled]="!roleType.value && !permissionType.value"
```

* Com valor da variavél:
```ts
 [disabled]="!newRole.typeName && !newRole.permission"
```

2022-05-09 19:44 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newLevel?.length == 0"
```ts
[disabled]="!newLevel"
```
Ou do outro jeito com referência local

2022-05-09 19:44 UTC, augustoicaro commented on src/app/shared/guards/auth.guard.ts
> +              };
É que está errado mesmo. cada um deve ter um `parent` diferente. O de administrador está certo. O de membro deve ser `Associado` e o de financeiro deve ser `Diretor Financeiro`.

2022-05-09 21:00 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newLevel?.length == 0"
Feito

2022-05-09 21:00 UTC, Elygledson commented on src/app/shared/guards/auth.guard.ts
> +              };
Alterado

2022-05-09 21:52 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +                  [disabled]="newRole.typeName?.length !== 0 && newRole.permission?.length !== 0 ? false : true"
Feito

2022-05-10 01:29 UTC, Elygledson commented on playground.mongodb
> +});
Feito

2022-05-11 00:19 UTC, augustoicaro approved these changes

2022-05-11 22:18 UTC, merged