[NWS-1321][NWS-1368] Handle article changes in position and level lists
ninc-management/plataforma pull request #179
Opened 2022-05-06 23:49 UTC by EduhFarias

2022-05-10 00:28 UTC, leo-holanda requested changes

2022-05-10 00:28 UTC, leo-holanda commented on src/app/pages/profile/profile.component.ts
> +          const simpliedWord = word
Seria simplified aqui?

2022-05-10 00:41 UTC, EduhFarias commented on src/app/pages/profile/profile.component.ts
> +    assessor: { o: 'Assesor', a: 'Assesora' },
Feito, que vacilo!

2022-05-10 00:41 UTC, EduhFarias commented on src/app/pages/profile/profile.component.ts
> +    assossiado: { o: 'Assossiado', a: 'Assossiada' },
Feito, que vacilo!

2022-05-10 00:41 UTC, EduhFarias commented on src/app/pages/profile/profile.component.ts
> +          const simpliedWord = word
Feito, que vacilo!

2022-05-10 00:57 UTC, leo-holanda approved these changes

2022-05-12 20:42 UTC, augustoicaro requested changes
Dá uma simplifica fazendo o que sugeri :)

2022-05-12 20:42 UTC, augustoicaro commented on src/app/pages/profile/profile.component.ts
> +          if ((this.positionsList as IIndexable)[simplifiedWord])
Nem precisava dessa complicação toda, era mais simples mandar um `as any` e tirar essa interface lá em cima. Aquilo que falamos ontem sobre apagar tipo.

2022-05-13 06:59 UTC, augustoicaro approved these changes

2022-05-13 07:00 UTC, merged