[NWS-1172][NWS-1270] Visual effect for notification of each new
ninc-management/plataforma pull request #191
Opened 2022-05-12 20:52 UTC by Elygledson

2022-05-12 23:22 UTC, EduhFarias approved these changes

2022-05-13 19:23 UTC, augustoicaro requested changes
Adiciona os comentários que pedi

2022-05-13 19:23 UTC, augustoicaro commented on backend/src/routes/notification.ts
>      UserModel.findByIdAndUpdate(
Adiciona um comentário no inicio de cada rota falando que a rota espera que o `from` e o `to` sejam objetos do tipo user.

2022-05-13 19:23 UTC, augustoicaro commented on backend/src/routes/notification.ts
>      UserModel.findByIdAndUpdate(
@EduhFarias esse correção não é a mesma que tu fez na tua tarefa? Aparentemente não precisavamos dele, houve um prolema de comunicação aqui. @Elygledson por que tu não falou que tinha corrigido o problema de apaga a notificação?

2022-05-13 19:23 UTC, augustoicaro commented on src/app/@theme/components/header/animation.ts
> +    '1s 0.5s',
Por que temos um delay de 0.5?

2022-05-14 18:24 UTC, augustoicaro approved these changes

2022-05-14 18:26 UTC, merged