[NWS-1172][NWS-1433] Handle database cache when a notification is read
ninc-management/plataforma pull request #192
Opened 2022-05-13 00:24 UTC by EduhFarias

2022-05-13 20:58 UTC, augustoicaro requested changes
Eduardo, precisamos padronizar o que essa rota recebe e explicitar isso num comentário de cada rota, assim como no envio do dado pelo serviço. Vamos acertar então que sempre vamos enviar um objeto de usuário.

2022-05-17 22:04 UTC, augustoicaro commented
@leo-holanda, não esquece de revisar esse aqui

2022-05-17 22:05 UTC, augustoicaro approved these changes

2022-05-17 22:32 UTC, leo-holanda approved these changes

2022-05-18 00:19 UTC, merged