[NWS-1311][NWS-1315] Separate another functions from report to separate files
ninc-management/plataforma pull request #201
Opened 2022-05-18 23:44 UTC by WilamisAviz15

2022-05-18 23:51 UTC, WilamisAviz15 commented
![Untitled999](https://user-images.githubusercontent.com/58791888/169173677-6066f8d6-013b-4e4b-9ba6-d6084d45c17e.png)

2022-05-19 23:04 UTC, leo-holanda requested changes

2022-05-19 23:04 UTC, leo-holanda commented on src/app/shared/report-generator.ts
> +  data: any,
Poderia ser uma boa deixar o tipo do data como Record<string, ReportValue>, já que ele vem da função computeReportDataBySector. Ela retorna um observável mas como a gente faz o subscribe então acredito que o tipo acabaria sendo esse

2022-05-19 23:08 UTC, augustoicaro approved these changes
Ao fazer a correção do Leo lebrar de fazer o pull do branch, já que fiz um rebase

2022-05-24 03:15 UTC, augustoicaro commented
@leo-holanda, dá uma olhada aqui depois para ver se está tudo certo.

2022-05-26 22:37 UTC, leo-holanda approved these changes

2022-05-26 22:39 UTC, merged