[NWS-1357][NWS-1443] Replace utils.service with utils.ts
ninc-management/plataforma pull request #205
Opened 2022-05-19 01:41 UTC by EduhFarias

2022-05-20 22:28 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.html
> +        *ngIf="isPhone()"
Concordo

2022-05-20 22:29 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +                {{ [comment.created] | transformPipe: this.formatDate }}
Não precisa, mas ele compila sem dar erro se iver, por isso deve ter passado despercebido.

2022-05-20 23:26 UTC, EduhFarias commented on src/app/@theme/components/header/header.component.html
> +        *ngIf="isPhone()"
Feito!

2022-05-20 23:26 UTC, EduhFarias commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +                {{ [comment.created] | transformPipe: this.formatDate }}
Feito!

2022-05-20 23:36 UTC, leo-holanda approved these changes

2022-05-24 03:12 UTC, augustoicaro requested changes
Não entendi por que você apagou os testes. Os testes devem mudar de pasta e serem realizados do mesmo jeito. Será um `utils.spec.ts`. Põe o teste d volta no local certo e ajeita alguns detalhes no arquivo. O Testing module está certo.

2022-05-24 23:59 UTC, augustoicaro approved these changes

2022-05-25 00:00 UTC, merged