[NWS-1409][NWS-1455] Add an input for the company name to social
ninc-management/plataforma pull request #208
Opened 2022-05-20 02:00 UTC by Elygledson

…load the config name

2022-05-20 02:02 UTC, Elygledson commented
![2022-05-19 (6)](https://user-images.githubusercontent.com/47836992/169433772-efa29e67-651d-4bf4-a0c2-fe668bcaa85f.png)

2022-05-20 23:06 UTC, WilamisAviz15 approved these changes

2022-05-24 03:30 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei

2022-05-24 03:30 UTC, augustoicaro commented on src/app/@theme/components/footer/footer.component.ts
> +      © {{ year }} {{ companyName }}. Template criado com ❤️ por
Trocar `template criado com` para `Plataforma de gestão criada com`

2022-05-24 03:30 UTC, augustoicaro commented on src/app/@theme/components/footer/footer.component.ts
> +      .pipe(takeUntil(this.destroy$))
Fazer `skipWhile` pegando o `isDataLoaded` do serviço

2022-05-24 03:30 UTC, augustoicaro commented on src/app/@theme/components/footer/footer.component.ts
> +        if (configs[0]) this.companyName = configs[0].socialConfig.companyName;
Assim não vamos precisar desse `if`

2022-05-24 03:30 UTC, augustoicaro commented on src/app/@theme/components/footer/footer.component.ts
> +      .getConfig()
Provavlemente você vai precisar de um `combneLatest` com o `isDataLoaded` dele

2022-05-24 03:30 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.ts
> +        this.menuTitle = config[0].socialConfig.companyName;
Mesma coisa aqui. Faz o `skipWhile`, remove toda esse linha do `if` e tudo certo

2022-05-24 19:43 UTC, Elygledson commented on src/app/@theme/components/footer/footer.component.ts
> +      .pipe(takeUntil(this.destroy$))
Feito.

2022-05-25 22:41 UTC, augustoicaro approved these changes

2022-05-25 22:55 UTC, merged