[NWS-1409][NWS-1457] Change Nortan name to company name in public.component.html
ninc-management/plataforma pull request #210
Opened 2022-05-20 22:56 UTC by Elygledson

2022-05-20 23:33 UTC, leo-holanda approved these changes
Tu testasse o caso do input do companyName no config ser vazio? Porque com a sigla do contrato o meu dava undefined aí pensei se esse caso não poderia ocorrer. E se puder também o print com a alteração

2022-05-20 23:41 UTC, Elygledson commented
![2022-05-20 (1)](https://user-images.githubusercontent.com/47836992/169625064-18f9deb8-04ab-46cc-b413-6d7a1271aed4.png)

2022-05-24 08:05 UTC, augustoicaro commented
> ![2022-05-20 (1)](https://user-images.githubusercontent.com/47836992/169625064-18f9deb8-04ab-46cc-b413-6d7a1271aed4.png)

Essa foto não corresponde ao que foi alterado nessa tarefa. Isso você fez na tarefa passada. Aqui você alterou a página pública do curso.

2022-05-24 08:06 UTC, augustoicaro commented
> Pelo que vi o código tá OK. Tu testasse o caso do input do companyName no config ser vazio? Porque com a sigla do contrato o meu dava undefined aí pensei se esse caso não poderia ocorrer. E se puder também o print com a alteração

O company name é um campo requerido com valor padrão d string vazio, logo ele sempre deve existir.

2022-05-24 08:08 UTC, augustoicaro requested changes
Dá uma olhada no ponto que falei.

2022-05-24 08:08 UTC, augustoicaro commented on src/app/public/public.component.ts
> +        if (configs[0]) this.config = configs[0];
Trocar aqui para a estrategia do `skipWhile` e remover o if, já que config sempre vai existir,

2022-05-26 23:19 UTC, augustoicaro approved these changes

2022-05-26 23:32 UTC, merged