[NWS-1409][NWS-1450] Change min character limit to creation of sectors and times to 2 characters
ninc-management/plataforma pull request #211
Opened 2022-05-23 23:12 UTC by WilamisAviz15

2022-05-23 23:12 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/169919001-3f8a240d-df73-4b5b-b09e-8f75955b09e9.png)

2022-05-24 01:29 UTC, Elygledson approved these changes

2022-05-24 08:14 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei. @Elygledson também dá uma olhada nos pontos para prestar mais atenção nisso nas próximas revisões.

2022-05-24 08:14 UTC, augustoicaro commented on src/app/pages/teams/team-item/team-item.component.html
> +              </p>
Isso aqui nunca vai acontcer já que esse input não é requeido

2022-05-24 08:14 UTC, augustoicaro commented on src/app/pages/teams/team-item/team-item.component.html
> +              </p>
mesma coisa aqui

2022-05-24 08:14 UTC, augustoicaro commented on src/app/pages/teams/team-item/team-item.component.html
> +                [disabled]="!sectorNameInput.dirty || !sectorAbrevInput.dirty"
Essa condição não está certa. Na imagem que você anexou dá para ver isso. Os  2 campos são invalidos e mesmo assim você deixa o botão de adicionar ativo.

2022-05-25 23:43 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170386965-69e18efb-4bda-40bf-837c-cf8256ca83ed.png)

2022-05-25 23:43 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170387000-2e477464-ea6c-4b34-bd55-5ffab2c63745.png)

2022-05-25 23:44 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170387041-0f542813-bfb2-4831-9540-e87a9f297fff.png)

2022-05-26 00:56 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170393226-9900e3a7-55e0-45e6-b780-c3e03571d965.png)

2022-05-26 00:57 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170393317-ef950110-6d20-4e12-b875-43b9eaed76c9.png)

2022-05-26 00:58 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/170393383-7538017c-e965-47c9-94aa-0f3f893a45bf.png)

2022-05-26 22:40 UTC, augustoicaro approved these changes

2022-05-26 22:41 UTC, merged