[NWS-1224][NWS-1225] Review Database migration steps
ninc-management/plataforma pull request #220
Opened 2022-05-27 00:31 UTC by augustoicaro

2022-05-27 20:03 UTC, leo-holanda approved these changes

2022-05-27 20:03 UTC, leo-holanda commented on playground.mongodb
> +db.teams.replaceOne({ _id: t._id }, t);
Acho que as variáveis poderiam ter nomes mais sugestivos, mesmo que o significado esteja por perto. Além de manter a consistência com o restante do código

2022-05-27 20:03 UTC, leo-holanda commented on playground.mongodb
> +db.teams.replaceOne({ _id: t._id }, t);
Acho que as variáveis poderiam ter nomes mais sugestivos, mesmo que o significado esteja por perto. Além de manter a consistência com o restante do código

2022-05-27 20:03 UTC, leo-holanda commented on playground.mongodb
> +  delete u.emailNortan;
Mesmo ponto do nome lá embaixo

2022-05-27 20:03 UTC, leo-holanda commented on playground.mongodb
> +  delete u.emailNortan;
Mesmo ponto do nome lá embaixo

2022-05-27 20:04 UTC, leo-holanda requested changes

2022-05-27 20:04 UTC, leo-holanda commented
Aprovei sem querer, mas depois requisitei as mudanças

2022-05-27 22:02 UTC, augustoicaro commented on playground.mongodb
> +    codeAbbreviation: '',
Ah, não me atentei nesse espaço, ajeitar aqui

2022-05-27 22:03 UTC, augustoicaro commented on playground.mongodb
> +db.teams.replaceOne({ _id: t._id }, t);
Vou alterar aqui

2022-05-27 22:04 UTC, augustoicaro commented on playground.mongodb
> +    codeAbbreviation: '',
Ajeitar também

2022-05-30 21:56 UTC, augustoicaro commented
@leo-holanda, já fiz as correṍes que tu solicitou. Revisa novamente depois aqui.

2022-05-30 22:33 UTC, leo-holanda approved these changes

2022-06-02 23:06 UTC, merged