[NWS-1409][NWS-1502] Uses added setting to disable OneDrive
ninc-management/plataforma pull request #226
Opened 2022-05-28 17:29 UTC by Elygledson

2022-05-30 17:28 UTC, leo-holanda requested changes

2022-05-30 17:28 UTC, leo-holanda commented on src/app/shared/services/onedrive.service.ts
> +export class OnedriveService implements OnDestroy {
Acho que seria um boa alterar o nome pra OneDriveService pra manter a consistência do cammelCase

2022-05-30 21:15 UTC, Elygledson commented on src/app/shared/services/onedrive.service.ts
> +export class OnedriveService implements OnDestroy {
Feito

2022-05-30 21:17 UTC, Elygledson commented on src/app/shared/services/contract.service.spec.ts
>      mockedOneDrive.isActive = true;
Removi este expenseType do config. Não precisava adicionar nas configurações para este teste.

2022-05-30 22:32 UTC, leo-holanda approved these changes

2022-06-02 23:36 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei

2022-06-02 23:36 UTC, augustoicaro commented on src/app/shared/services/contract.service.spec.ts
> +    let mockedOneDrive = new OneDrive();
`let mockedOneDriveConfig = new OneDriveConfig();`

Trocar no config o nome do modelo para `OneDriveConfig` assim como todos os outros.

2022-06-02 23:36 UTC, augustoicaro commented on src/app/shared/services/metrics.service.spec.ts
> +    configReq.flush([]);
Por que estamos passando o config vazio aqui? Isso nunca acontece na plataforma, ao menos devemos passar o nosso config padrão inicial:

```ts
const config = {
  expenseTypes: [],
  invoiceConfig: {
    hasType: true,
    hasHeader: true,
    hasTeam: true,
    hasPreliminary: true,
    hasExecutive: true,
    hasComplementary: true,
    hasStageName: true,
    hasImportants: true,
    hasMaterialList: true,
    nfPercentage: '0,00',
    organizationPercentage: '0,00',
    codeAbbreviation: '',
  },
  profileConfig: {
    positions: [],
    hasLevels: true,
    levels: [],
    hasTeam: true,
    hasSector: true,
    hasExpertiseBySector: true,
  },
  socialConfig: {
    youtubeLink: '',
    linkedinLink: '',
    instagramLink: '',
    glassfrogLink: '',
    gathertownLink: '',
    companyName: '',
  },
  modulesConfig: {
    hasPromotion: true,
    hasCourse: true,
  },
  oneDriveConfig: {
    isActive: false,
  }
};
```

2022-06-02 23:36 UTC, augustoicaro commented on src/app/shared/services/storage.service.spec.ts
> +    configReq.flush([]);
Mesma coisa aqui. Nunca passamos um config vazio na pltaforma, não faz sentido fazer isso no teste

2022-06-03 22:18 UTC, Elygledson commented on src/app/shared/services/metrics.service.spec.ts
> +    configReq.flush([]);
Feito!

2022-06-03 22:35 UTC, Elygledson commented on src/app/shared/services/onedrive.service.ts
> +    combineLatest([this.configService.isDataLoaded$, this.configService.getConfig()])
Feito!

2022-06-03 22:45 UTC, Elygledson commented on src/app/shared/services/onedrive.service.ts
>      return of('');
Feito!

2022-06-04 13:57 UTC, augustoicaro approved these changes

2022-06-04 14:13 UTC, merged