[NWS-1354][NWS-1495] Notify team member when receives the full contract value
ninc-management/plataforma pull request #228
Opened 2022-05-31 00:33 UTC by WilamisAviz15

2022-05-31 00:33 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/171071393-c85b37cc-b54e-46a9-aba0-f1d973b31e8f.png)

2022-05-31 00:35 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/171071450-cc909775-5733-47d4-8614-26736faa5ffb.png)

2022-06-02 11:20 UTC, Elygledson commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +    private notificationService: NotificationService
Seria bom jogar esse notificationService para cima para ficar junto com os privates antes do public. É só um detalhe mesmo que os demais construtores possuem na ordem.

2022-06-02 11:23 UTC, Elygledson approved these changes

2022-06-02 23:52 UTC, augustoicaro requested changes
Dá uma olhada nesse ponto que levantei

2022-06-02 23:52 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +    private notificationService: NotificationService
É verdade

2022-06-02 23:52 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +      if (notPaidValue === '0,00') {
Adicionar aqui também a comparação do `valueReceived` para tratarmos o caso de recebimento total o pagamento em OP diferentes para cada membro, tendo apenas uma notificação para cada um.

Nessa linha somente vai ter a notificação se o membro do time não tem nada para receber e está recebendo o que faltava nessa OP

2022-06-02 23:53 UTC, augustoicaro commented
Aproveita e faz o rabase

2022-06-08 01:06 UTC, WilamisAviz15 commented
Correçoes feitas

2022-06-09 01:52 UTC, augustoicaro approved these changes

2022-06-09 01:54 UTC, merged