[NWS-1351][NWS-1516] Display confirmation dialog to dismiss data from contract management tab
ninc-management/plataforma pull request #232
Opened 2022-06-01 00:25 UTC by EduhFarias

Esse branch é com base no NWS-1507

2022-06-02 14:58 UTC, leo-holanda requested changes

2022-06-02 22:56 UTC, EduhFarias commented on src/app/pages/contracts/contract-item/management-tab/checklist-item-dialog/checklist-item-dialog.component.ts
> +    private dialogService: NbDialogService
Feito

2022-06-03 00:01 UTC, leo-holanda approved these changes

2022-06-03 00:48 UTC, augustoicaro approved these changes

2022-06-03 00:49 UTC, merged