[NWS-1354][NWS-1489] Commitment/Payment/Expense Order Created
ninc-management/plataforma pull request #234
Opened 2022-06-02 00:09 UTC by Elygledson

… Financial)

2022-06-02 23:24 UTC, EduhFarias requested changes
Opa Elygledson, eu deixei uns comentários e caso não fique claro só perguntar

2022-06-02 23:24 UTC, EduhFarias commented on src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
> +
Essa função aqui se repete algumas vezes, o que poderia ser feito é criar ela em um arquivo compartilhado e colocar a mensagem como um parâmetro, daí você poderia enviar qualquer mensagem usando uma única função.

2022-06-02 23:24 UTC, EduhFarias commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +
Essa função aqui se repete algumas vezes, o que poderia ser feito é criar ela em um arquivo compartilhado e colocar a mensagem como um parâmetro, daí você poderia enviar qualquer mensagem usando uma única função.

2022-06-02 23:24 UTC, EduhFarias commented on src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
> +
Essa função aqui se repete algumas vezes, o que poderia ser feito é criar ela em um arquivo compartilhado e colocar a mensagem como um parâmetro, daí você poderia enviar qualquer mensagem usando uma única função.

2022-06-03 22:29 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
> +
Concordo com o Eduardo, não tínhamos falado sobre unificar essa função durante a semana?

2022-06-03 22:39 UTC, augustoicaro requested changes
Adicionalmente aos pontos do Eduardo vê esses meus pontos. Aproveita também para fazer um rebase

2022-06-03 22:39 UTC, augustoicaro commented on backend/src/models/platformConfig.ts
> +import mongooseUniqueValidator from 'mongoose-unique-validator';
Se lembra que testamos esse unique validator e não deu certo? Remove tudo relacionado a ele por favor

2022-06-03 22:39 UTC, augustoicaro commented on backend/src/models/platformConfig.ts
> +  @prop({ required: true, unique: true })
Mesma coisa para o `unique`

2022-06-03 22:39 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +  PARENTS = ['Diretor de T.I', 'Diretor Financeiro', 'Associado'];
Essas aqui não precisam, vão sair em breve porque é específico da Nortan

2022-06-03 22:39 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +      (pos) => pos.roleTypeName === this.newRole.roleTypeName || this.PARENTS.includes(this.newRole.roleTypeName)
Que implica alterar aqui

2022-06-03 23:18 UTC, Elygledson commented on backend/src/models/platformConfig.ts
> +import mongooseUniqueValidator from 'mongoose-unique-validator';
Feito!

2022-06-03 23:19 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  PARENTS = ['Diretor de T.I', 'Diretor Financeiro', 'Associado'];
por enquanto, deixei.

2022-06-03 23:19 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +      (pos) => pos.roleTypeName === this.newRole.roleTypeName || this.PARENTS.includes(this.newRole.roleTypeName)
também

2022-06-06 23:05 UTC, Elygledson commented on src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
> +
feito

2022-06-06 23:05 UTC, Elygledson commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +
feito

2022-06-06 23:05 UTC, Elygledson commented on src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
> +
feito

2022-06-07 23:26 UTC, EduhFarias approved these changes

2022-06-07 23:32 UTC, augustoicaro approved these changes
Dá uma olhada nas pequnas revisões que passei e aproveita e faz um rebase para o `main`

2022-06-07 23:32 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
> +        message: `${expenseAuthor.fullName} criou a ordem de despesa no valor de R$${this.expense.value} no contrato ${this.contract.code}.`,
Trocar para: `${expenseAuthor.article}  ${expenseAuthor.fullName} criou uma transação de despesa no valor de R$${this.expense.value} no contrato ${this.contract.code}.`

2022-06-07 23:32 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +      message: `O gestor do contrato ${this.contract.fullName} criou a ordem de pagamento no valor de R$${this.payment.value} no contrato ${this.contract.code}.`,
Altera aqui também para : `${this.contract.article} ${this.contract.article == "a" ? gestora : gestor} do contrato ${this.contract.fullName} criou a ordem de pagamento no valor de R$${this.payment.value} no contrato ${this.contract.code}.`

2022-06-07 23:32 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.ts
> +      message: `O gestor do contrato ${this.contract.fullName} criou a ordem de empenho no valor de R$${this.receipt.value} no contrato ${this.contract.code}.`,
Trocar para: `this.contract.article} ${this.contract.article == "a" ? gestora : gestor} do contrato ${this.contract.fullName} criou a ordem de empenho no valor de R$${this.receipt.value} no contrato ${this.contract.code}.`,

2022-06-08 00:07 UTC, Elygledson commented on src/app/pages/contracts/contract-item/expense-item/expense-item.component.ts
> +        message: `${expenseAuthor.fullName} criou a ordem de despesa no valor de R$${this.expense.value} no contrato ${this.contract.code}.`,
Feito.

2022-06-08 01:05 UTC, Elygledson commented on src/app/pages/contracts/contract-item/payment-item/payment-item.component.ts
> +      message: `O gestor do contrato ${this.contract.fullName} criou a ordem de pagamento no valor de R$${this.payment.value} no contrato ${this.contract.code}.`,
Feito.

2022-06-08 01:12 UTC, Elygledson commented
@augustoicaro pronto, fiz o rebase para main

2022-06-09 21:00 UTC, merged