[NWS-1351][NWS-1529] Display confirmation dialog to dismiss data from invoice
ninc-management/plataforma pull request #239
Opened 2022-06-03 23:28 UTC by EduhFarias

Dialogo de confirmação em um orçamento alterado:

![dialog](https://user-images.githubusercontent.com/30202709/171966510-01d3fccc-b505-4b2f-99e1-cf4ac902a851.png)

2022-06-06 15:10 UTC, leo-holanda requested changes

2022-06-06 15:10 UTC, leo-holanda commented on src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
> +            question: 'Deseja descartar as alterações feitas',
Seria uma boa colocar uma interrogação no final da string question. Eu vi que tem outros diálogos que também faltam essa interrogação mas talvez a gente possa ir consertando nas tasks

2022-06-06 23:21 UTC, augustoicaro approved these changes

2022-06-06 23:21 UTC, augustoicaro commented on src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
> +            question: 'Deseja descartar as alterações feitas',
Eita, é verdade

2022-06-07 22:56 UTC, EduhFarias commented on src/app/pages/invoices/invoice-dialog/invoice-dialog.component.ts
> +            question: 'Deseja descartar as alterações feitas',
Feito

2022-06-08 19:15 UTC, leo-holanda approved these changes

2022-06-09 21:01 UTC, merged