Notify contract author when 3 days are missing and every 3 days late to dueDate OE
ninc-management/plataforma pull request #240
Opened 2022-06-07 02:48 UTC by WilamisAviz15

2022-06-07 02:49 UTC, WilamisAviz15 commented
Os dois casos (backend):
![image](https://user-images.githubusercontent.com/58791888/172285205-e497cef0-6df6-4603-9543-393c196509f7.png)

2022-06-07 02:50 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/172285361-c5d2ab71-b3ed-41f0-b0b2-52a67aa154a0.png)

2022-06-07 23:23 UTC, EduhFarias approved these changes

2022-06-08 00:08 UTC, augustoicaro requested changes
Dá uma olhada nesses 2 pontos que levantei por favor.

2022-06-08 00:08 UTC, augustoicaro commented on backend/src/routes/notification.ts
> +        }
Tentar mover funções para o `shared/util.ts`

2022-06-08 00:08 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/receipt-item/receipt-item.component.html
> +          <label class="label" for="input-paidDate">Previsão do pgto:</label>
Trocar label para `Será pago em:`

2022-06-08 01:19 UTC, WilamisAviz15 commented
alterações feitas

2022-06-09 21:03 UTC, augustoicaro approved these changes

2022-06-09 21:05 UTC, merged