[NWS-1351][NWS-1538] Display confirmation dialog to dismiss data from config
ninc-management/plataforma pull request #246
Opened 2022-06-08 23:28 UTC by EduhFarias

2022-06-14 23:48 UTC, Elygledson commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
Como estávamos falando em organizar esta semana os imports então acho que seria bom iniciar aqui.

Segue a ordem:
módulos do angular
enter
serviços
enter
modelos
enter 
validadores (o arquivo.json caso esteja utilizando)

2022-06-14 23:57 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
Como estávamos falando em organizar esta semana os imports então acho que seria bom iniciar aqui.

Segue a ordem:
módulos do angular
enter
components,serviços
enter
modelos
enter 
validadores (o arquivo.json caso esteja utilizando)

2022-06-15 00:06 UTC, Elygledson requested changes
dá uma olhada na organização destes imports, por favor.

2022-06-15 23:12 UTC, EduhFarias commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
Feito

2022-06-15 23:26 UTC, augustoicaro approved these changes

2022-06-15 23:29 UTC, Elygledson approved these changes

2022-06-15 23:46 UTC, merged