[NWS-1224][NWS-1556] Fix prospect approval bug
ninc-management/plataforma pull request #251
Opened 2022-06-10 23:19 UTC by leo-holanda

2022-06-15 00:10 UTC, Elygledson commented on backend/src/routes/auth.ts
Talvez seria bom já organizar estes imports. 

Ordem:
módulos do angular
enter
componentes, serviços..
enter
modelos
enter 
validadores (o arquivo.json caso esteja utilizando)

2022-06-15 00:13 UTC, Elygledson commented on backend/src/routes/user.ts
aqui também.

2022-06-15 00:21 UTC, Elygledson requested changes
dá uma olhada nos comentários

2022-06-15 19:15 UTC, leo-holanda commented on backend/src/routes/auth.ts
Eu dei uma organizada neles, mas não sei se ficou do jeito que tu tava imaginando, já que não havia algumas categorias que tu citou por serem arquivos de rota do backend. Coloquei os imports do NPM primeiro, no fim os modelos e no meio os imports dos mapas globais

Mas acho que seria uma boa definir a ordenação definitiva que englobe todas as categorias de imports e com ela configurar uma funcionalidade de ordenação de imports do ESLint. Essa parte ficaria toda automatizada, o que seria massa. Esse [link](https://dev.to/diballesteros/how-to-quickly-configure-eslint-for-import-sorting-2h73) fala sobre isso

2022-06-21 23:17 UTC, augustoicaro approved these changes

2022-06-21 23:18 UTC, Elygledson approved these changes

2022-06-21 23:19 UTC, merged