[NWS-1224][NWS-1582] Add percentage inputs per team
ninc-management/plataforma pull request #259
Opened 2022-06-21 09:56 UTC by Elygledson

2022-06-21 09:58 UTC, Elygledson commented
![2022-06-21](https://user-images.githubusercontent.com/47836992/174773046-3d617471-ccbf-4115-b8ca-76c49a362dce.png)

2022-06-22 00:19 UTC, EduhFarias commented on backend/src/models/team.ts
> +  changePercentage: boolean = false;
Essa propriedade precisa mesmo ir para o banco? Acho que não, poderia ser uma propriedade que sempre inicia falsa e caso o usuário coloque como verdadeira, após atualizar ou reabrir as configs ela voltaria ao estado de falso

2022-06-22 00:20 UTC, EduhFarias commented on playground.mongodb
> +  team.changePercentage = false;
Mesmo caso, a propriedade é mesmo necessária no banco?

2022-06-22 00:21 UTC, EduhFarias commented on src/app/@theme/components/header/config/config.component.html
> -            name="toggle-isDuplicated"
O nome do toggle interfere em algo?

2022-06-22 00:22 UTC, Elygledson commented on backend/src/models/team.ts
> +  changePercentage: boolean = false;
Faz sentido mesmo! Vou rever aqui.

2022-06-22 00:22 UTC, EduhFarias requested changes
Dá uma olhada nos comentários, ainda pode ser que a alteração seja desnecessária

2022-06-22 00:26 UTC, leo-holanda requested changes

2022-06-22 00:26 UTC, leo-holanda commented on src/app/pages/teams/team-item/team-item.component.html
> +          <label class="label-divider">Porcentagens da organização e nota fiscal</label>
Acho que precisa puxar essa classe label-divider de algum canto que usa ela. Pelo que vi ela não tá no scss do team-item.component

2022-06-22 00:26 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> -            name="toggle-isDuplicated"
Eu quis aqui dá mais sentido para ficar algo mais geral para quando alguém quisesse ativar uma toggle ocultar e desocultar algum elemento.

2022-06-22 00:29 UTC, Elygledson commented on src/app/pages/teams/team-item/team-item.component.html
> +          <label class="label-divider">Porcentagens da organização e nota fiscal</label>
vou dá uma olhada aqui

2022-06-22 00:48 UTC, Elygledson commented on src/app/pages/teams/team-item/team-item.component.html
> +          <label class="label-divider">Porcentagens da organização e nota fiscal</label>
Ah, Leo bem observado porém eu não sei agora se esse <hr> deve ser branco como nas configurações em lista de despesas ai por isso não coloquei. @augustoicaro  estes divisores devem seguir o mesmo padrão de estilo das configurações?

2022-06-22 23:21 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que comentei po favor

2022-06-22 23:21 UTC, augustoicaro commented on backend/src/models/team.ts
> +  changePercentage: boolean = false;
Nesse caso temos 2 opções, não salvar no banco e inferir esse caro verificando se `organizationPercentage` e `nfPercentage` não são vazios, ou salvar no banco. Acho que salvar no banco é a opção mais simples. Sugiro trocar o nome para `overridePercentages`.

2022-06-22 23:21 UTC, augustoicaro commented on playground.mongodb
> +  team.changePercentage = false;
Deixaria salvo seguindo o comentário anteior de ir pelo mais simples

2022-06-22 23:21 UTC, augustoicaro commented on src/app/pages/teams/team-item/team-item.component.html
> +          <label class="label-divider">Porcentagens da organização e nota fiscal</label>
Exato, seguir o mesmo estilo.

2022-06-22 23:21 UTC, augustoicaro commented on src/app/pages/teams/team-item/team-item.component.html
> +          <nb-toggle [(ngModel)]="team.changePercentage" name="toggle-hide" labelPosition="start">Alterar</nb-toggle>
Esse nome não ficou bom. Tenta trocar de `Alterar` para `Sobrepor`

2022-06-27 23:15 UTC, EduhFarias approved these changes

2022-06-28 21:25 UTC, augustoicaro approved these changes

2022-06-28 21:26 UTC, merged