[NWS-919][NWS-1569] Remove ng2-smart-table from package.json and replace use of components
ninc-management/plataforma pull request #273
Opened 2022-06-27 00:57 UTC by WilamisAviz15

2022-06-27 00:59 UTC, WilamisAviz15 commented
Invoices: ![image](https://user-images.githubusercontent.com/58791888/175841803-59c64d99-d662-45b7-92f6-ee90a9701cf0.png)

Contracts: 
![image](https://user-images.githubusercontent.com/58791888/175841822-c9e1dfee-0396-44d7-a90e-ab04273cbd90.png)

Contractors: 
![image](https://user-images.githubusercontent.com/58791888/175841849-5b0ee308-f4ad-44b4-bbef-a4a011f2af5c.png)

Users: 
![image](https://user-images.githubusercontent.com/58791888/175841860-0f2c8edf-21fb-4753-a341-40115eae3213.png)

Teams: 
![image](https://user-images.githubusercontent.com/58791888/175841873-2b067ff3-22ec-4656-a479-7828cb060dba.png)

Promotions: 
![image](https://user-images.githubusercontent.com/58791888/175841884-aa2ee5ed-02fc-4413-8d18-bdfedcedc7f4.png)

Courses: 
![image](https://user-images.githubusercontent.com/58791888/175841898-8ce01bae-6f65-4f66-86a2-4d4b4dddcf74.png)

2022-06-28 00:13 UTC, leo-holanda requested changes
Alguns pontos

2022-06-28 00:13 UTC, leo-holanda commented on src/app/@theme/components/smart-table/components/thead/cells/title/title.component.ts
> +          sortConf.forEach((fieldConf: any) => {});
Essa linha é necessária?

2022-06-28 00:13 UTC, leo-holanda commented on src/app/@theme/components/smart-table/lib/data-source/data-source.ts
> +import { Observable } from 'rxjs';
Seria uma boa colocar os dois imports como um só já que a fonte é a mesma

2022-06-28 00:13 UTC, leo-holanda commented on src/app/@theme/components/smart-table/lib/grid.ts
> +      });
Precisa desse catch? Pelo que vi ele se repete em outros lugares desse arquivo mas todos são vazios

2022-06-28 00:13 UTC, leo-holanda commented on src/app/@theme/components/smart-table/smart-table.component.scss
> +  nb-smart-table {
Uma classe vazia que pode ser interessante remover. Pelo que vi no CTRL + F ela não é usada no template

2022-06-28 22:54 UTC, WilamisAviz15 commented on src/app/@theme/components/smart-table/components/thead/cells/title/title.component.ts
> +          sortConf.forEach((fieldConf: any) => {});
realmente não precisa

2022-06-28 22:54 UTC, WilamisAviz15 commented on src/app/@theme/components/smart-table/lib/data-source/data-source.ts
> +import { Observable } from 'rxjs';
verdade

2022-06-28 22:56 UTC, WilamisAviz15 commented on src/app/@theme/components/smart-table/smart-table.component.scss
> +  nb-smart-table {
verdade

2022-06-28 23:59 UTC, leo-holanda approved these changes

2022-07-01 14:19 UTC, merged