[NWS-1378][NWS-1610] Override organization and NF percentages when enabled on team
ninc-management/plataforma pull request #279
Opened 2022-06-29 00:15 UTC by EduhFarias

2022-07-01 22:59 UTC, augustoicaro requested changes

2022-07-01 22:59 UTC, augustoicaro commented on src/app/shared/utils.ts
> +  const teamService = appInjector.get(TeamService);
Vamos precisar do invoice service

2022-07-01 22:59 UTC, augustoicaro commented on src/app/shared/utils.ts
> +    if (isOfType<Invoice>(iDocument.invoice, ['_id', 'author', 'nortanTeam', 'sector', 'code', 'type', 'contractor'])) {
- manter o typeguard do if acima como: `['_id', 'author', 'nortanTeam', 'sector', 'code', 'type', 'contractor', 'administration']`
- Remover isso e trocar linha de baixo para: `invoice = invoiceService.idToInvoice(contract.invoice)`

2022-07-04 15:53 UTC, leo-holanda approved these changes

2022-07-04 23:11 UTC, augustoicaro approved these changes

2022-07-04 23:13 UTC, merged