[NWS-1378][NWS-1649] Fix Notification Preview
ninc-management/plataforma pull request #286
Opened 2022-07-01 23:04 UTC by Elygledson

2022-07-01 23:05 UTC, Elygledson commented
![2022-07-01 (2)](https://user-images.githubusercontent.com/47836992/176976342-a076f412-2204-42a8-a628-6db079bebcab.png)

2022-07-05 00:10 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos por favor

2022-07-05 00:10 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
> +              <p [innerHTML]="[notification.message] | transformPipe: stringUtils.applyBoldToMention"></p>
Volta esse cara para pre, se não vai perder a marcação de negrito.

2022-07-05 00:10 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
>            <div class="row">
remover o style da linha 34 do `nb-card-body` e adicionar nesta div

2022-07-05 00:39 UTC, EduhFarias approved these changes

2022-07-05 21:56 UTC, augustoicaro requested changes

2022-07-05 21:56 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
> -      <nb-card-body style="padding: 0">
No caso geral imagino que queriamos manter esse padding 0 e somente no caso de notificação que temos que trocar o cara interno.

2022-07-05 21:56 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.html
> +          <div class="row" style="padding: 0 1rem; overflow-x: hidden;">
No caso aqui que o padding do cardboddy é 0, devemos adiciona os 1.rem de padding que você estava esperando ter. Nesse caso, precisa ser `0 2.5rem`

2022-07-06 21:55 UTC, Elygledson commented
![image](https://user-images.githubusercontent.com/47836992/177650120-df30efde-b7ab-4778-970c-94642436f7cb.png)
Foto da última atualização

2022-07-06 23:07 UTC, augustoicaro approved these changes

2022-07-06 23:08 UTC, merged