[NWS-1471][NWS-1643]Add eye icon to check if item is visible
ninc-management/plataforma pull request #296
Opened 2022-07-07 00:23 UTC by EduhFarias

Imagem com o ícone de visibilidade, ativado e desativado, ao lado dos itens de atividade:
![oie_Jdr0nR0edlDZ](https://user-images.githubusercontent.com/30202709/177663701-728bf8c5-3796-40d6-949e-a761bf21a248.png)

2022-07-07 13:44 UTC, leo-holanda approved these changes
Só um ponto em relação à conversão das datas.

2022-07-07 13:44 UTC, leo-holanda commented on src/app/pages/courses/course-item/course-item.component.ts
> +    this.iCourse.startDate = new Date(this.iCourse.startDate);
Eu pensava que essa data já vinha convertida em algum momento por algum reviveDates no caminho. Mas vi que na linha 56 também converte o this.course. Seria interessante ver se não faltou um reviveDates no meio do caminho pra não precisar fazer as conversões.

2022-07-15 22:28 UTC, augustoicaro requested changes

2022-07-15 22:28 UTC, augustoicaro commented on src/app/pages/courses/course-item/course-item.component.ts
> +    this.iCourse.startDate = new Date(this.iCourse.startDate);
Tem razão, não deveria precisar de conversão

2022-07-18 22:49 UTC, leo-holanda approved these changes
Acredito que a solução já resolve o problema nas datas, mas fiquei pensando se essa lógica não ficaria melhor no getCourses no serviço. O que tu acha?

2022-07-18 22:49 UTC, leo-holanda commented on src/app/pages/courses/courses.component.ts
> +          course.startDate = new Date(course.startDate);
Acho que uma boa também seria chamar o reviveDates no array de cursos do getCourses dentro do subscribe da requisição da API, como tem tipo no getContracts e getInvoices

2022-07-18 23:11 UTC, augustoicaro commented on src/app/pages/courses/courses.component.ts
> +          course.startDate = new Date(course.startDate);
Ah sim. Também era isso que estava esperando. Padroniza igual aos outros serviços por favor.

2022-07-18 23:13 UTC, augustoicaro approved these changes

2022-07-19 02:41 UTC, augustoicaro approved these changes

2022-07-19 02:42 UTC, merged