[NWS-1277][NWS-1279] Header e Sidebar
ninc-management/plataforma pull request #306
Opened 2022-07-14 23:36 UTC by Elygledson

2022-07-18 19:56 UTC, EduhFarias commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +      )
Precisa ser um combineLatest aqui?

2022-07-18 19:58 UTC, EduhFarias commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +  @ViewChild('sidebar', { static: false, read: ElementRef }) sidebarRef!: ElementRef<HTMLElement>;
Esse sidebarRef é usado em algum outro local?

2022-07-18 20:02 UTC, EduhFarias commented on src/app/@theme/components/header/header.component.ts
> +  }
Acredito que você poderia simplificar aqui usando a função toggle() do classList. Ela adiciona/remove uma classe dependendo de como esteja a lista atual.

2022-07-18 20:03 UTC, EduhFarias approved these changes

2022-07-18 23:15 UTC, augustoicaro commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +      )
Não precisa mesmo, bem observado.

2022-07-18 23:19 UTC, augustoicaro commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +  @ViewChild('sidebar', { static: false, read: ElementRef }) sidebarRef!: ElementRef<HTMLElement>;
Revisei aqui com o Eduardo e relamente não está sendo usado em nenhum outro local, deveria ter apagado esse aí

2022-07-18 23:23 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.ts
> +  }
```js
 displayIframe(): void {
    this.iframeRef.nativeElement.classList.toggle('active');
  }
```

2022-07-21 03:32 UTC, augustoicaro requested changes

2022-07-21 03:32 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.ts
> -      .subscribe((event: { item: any; tag: string }) => {
Você ainda não me explicou essa parte

2022-07-21 03:32 UTC, augustoicaro commented on src/app/@theme/layouts/one-column/one-column.layout.scss
> +  }
Nem essa

2022-07-22 00:44 UTC, Elygledson commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +      )
Feito

2022-07-22 00:44 UTC, Elygledson commented on src/app/@theme/layouts/one-column/one-column.layout.ts
> +  @ViewChild('sidebar', { static: false, read: ElementRef }) sidebarRef!: ElementRef<HTMLElement>;
Feito

2022-07-22 00:44 UTC, Elygledson commented on src/app/@theme/components/header/header.component.ts
> +  }
Massa.

2022-07-22 00:45 UTC, Elygledson commented on src/app/@theme/components/header/header.component.html
> +    src="https://app.slack.com/client/TRL92UC9G/CRL92UHHQ"
Feito

2022-07-22 22:34 UTC, Elygledson commented on src/app/@theme/layouts/one-column/one-column.layout.scss
> +  }
Feito

2022-07-22 23:41 UTC, augustoicaro approved these changes

2022-07-22 23:41 UTC, merged