[NWS-1224][NWS-1697] CNPJ mask in the platform configuration in the social tab
ninc-management/plataforma pull request #307
Opened 2022-07-15 00:21 UTC by Elygledson

2022-07-18 13:27 UTC, leo-holanda requested changes

2022-07-18 13:27 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +          !invoiceConfigform.valid ||
Como form seria uma palavra separada, pelo cammelCase acho que ficaria "invoiceConfigForm" e o equivalente para as outras referências

2022-07-18 18:36 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +          !invoiceConfigform.valid ||
Bem obervado eu fiz estas alterações na outra que vou enviar já já

2022-07-19 02:45 UTC, augustoicaro requested changes

2022-07-19 02:45 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.html
> +          !invoiceConfigform.valid ||
Qual outra? Lembra que cada tarefa dessa estória são correçÕes isoladas. Tudo relacionado a esse PR tem que estar aqui.

2022-07-19 22:35 UTC, augustoicaro approved these changes
Aprovei a outra, mas deixa esses pontos que levantei como nota para os próximos PR e correções.

2022-07-19 22:35 UTC, augustoicaro commented
Precisa fazer o rebase desse branch

2022-07-20 00:43 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +          !invoiceConfigform.valid ||
Feito

2022-07-20 00:44 UTC, Elygledson commented
@augustoicaro fiz o rebase.

2022-07-21 03:14 UTC, augustoicaro requested changes

2022-07-21 03:14 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.html
> +              [brmasker]="{ mask: '00.000.000/0000-00', len: 18 }"
Tu tirou essa mascara de onde? Somente a mascara não garante que o cara digitar o CNPJ todo. Então além disso precisa ter um validador de tamanho. Sugiro dar uma olhada em como fazemos no formulário de adição de cliente ou até no perfil para CPF. Temos uma configuração de mascara para isso.

2022-07-22 00:33 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +              [brmasker]="{ mask: '00.000.000/0000-00', len: 18 }"
Feito

2022-07-22 00:39 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +              [brmasker]="{ mask: '00.000.000/0000-00', len: 18 }"
Feito

2022-07-22 18:43 UTC, leo-holanda requested changes

2022-07-22 18:43 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +              [minlength]="validationUser.document.maxLength"
Acho que seria uma boa criar essa regra de validação pra dentro do config-validation.json e usar ela ao invés da que tem no user-validation.json. Só pra fins de separação mesmo já que pra user remete mais à CPF

2022-07-22 21:53 UTC, leo-holanda approved these changes

2022-07-27 02:43 UTC, augustoicaro approved these changes

2022-07-27 02:47 UTC, merged