Parameterize budget product list unit in configuration
ninc-management/plataforma pull request #313
Opened 2022-07-18 21:09 UTC by Elygledson

2022-07-18 23:27 UTC, EduhFarias approved these changes

2022-07-19 03:11 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei.

2022-07-19 03:11 UTC, augustoicaro commented on playground.mongodb
> +   config.invoiceConfig.units = ['m²','km','ha','dia','unidade'];
Faltou criar a função da migração da base da G4/Elo.

2022-07-19 03:11 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +        takeUntil(this.destroy$)
Aqui não precisava ter trocado para `takeUntil()` porque estamos nos aproveitando do fato que não conseguimos abrir as configurações de um item de qualquer coisa, por estarmos em um dialogo e dentro desse dialogo não ter um meio de abrir a configuração. Logo só precisamos carregar esse cara uma vez. Então quando tiver na dúvida é só tentar abrir a configuração, se conseguir será `takeUntil()`, se não será `take(1)`.

2022-07-19 22:43 UTC, Elygledson commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +        takeUntil(this.destroy$)
Feito

2022-07-21 03:38 UTC, augustoicaro approved these changes
Só faltou esse datalhe que levantei aqui.

2022-07-21 03:38 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +import { BehaviorSubject, combineLatest, Observable, of, Subject, takeUntil } from 'rxjs';
Só remove o `takeUntil` daqui já que não estamos usando ele mais.

2022-07-21 23:44 UTC, Elygledson commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +import { BehaviorSubject, combineLatest, Observable, of, Subject, takeUntil } from 'rxjs';
feito

2022-07-21 23:48 UTC, Elygledson commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +import { BehaviorSubject, combineLatest, Observable, of, Subject, takeUntil } from 'rxjs';
Feito

2022-07-21 23:49 UTC, merged