[NWS-1224][NWS-1698] Fix gross/liquid value not calculating when creating invoice
ninc-management/plataforma pull request #314
Opened 2022-07-18 23:05 UTC by leo-holanda

2022-07-19 03:15 UTC, augustoicaro requested changes

2022-07-19 03:15 UTC, augustoicaro commented on src/app/shared/utils.ts
> +  if (isOfType<Invoice>(iDocument, ['author', 'products', 'type', 'administration'])) {
Ah, isso foi vacilo meu. Estávamos fazendo uma coisa juntos e estranhei esse cara não ter todos os campos como em outros verificações de tipo que fazemos. Adiciona um comentário aqui por favor para não cometermos o mesmo erro no futuro explicando porque esse cara deve ser assim. Aproveita também para conferir como era nas versões passadas.

2022-07-19 03:15 UTC, augustoicaro commented on src/app/shared/utils.ts
> +  if (isOfType<Invoice>(iDocument, ['author', 'products', 'type', 'administration'])) {
O mesmo para esse.

2022-07-19 13:58 UTC, leo-holanda commented on src/app/shared/utils.ts
> +  if (isOfType<Invoice>(iDocument, ['author', 'products', 'type', 'administration'])) {
Blz!

2022-07-21 03:38 UTC, augustoicaro commented
@Elygledson não esquece de revisar essa aqui.

2022-07-22 19:10 UTC, leo-holanda commented on src/app/shared/services/invoice.service.ts
> +    if (isOfTypeNew(id, Invoice)) return id;
Eu coloquei o nome como isOfTypeNew porque se eu substituísse o antigo pelo novo, ia quebrar em vários lugares e o refactoring teria que ser feito em um PR só. Aí minha ideia foi colocar essa distinção e no último PR apagar a função antiga e só remover a distinção

2022-07-22 23:34 UTC, augustoicaro approved these changes
Bom trabalho! Ficou muito bom. Só ajusta aqueles ponto que falei durante a reunião.

2022-07-25 23:51 UTC, Elygledson approved these changes

2022-07-27 02:51 UTC, merged