[NWS-1224][NWS-1708]  Add checkmark icon in notification dialog header
ninc-management/plataforma pull request #325
Opened 2022-07-22 22:47 UTC by Elygledson

2022-07-25 22:47 UTC, Elygledson commented
![Screenshot](https://user-images.githubusercontent.com/47836992/180886849-e7889f2e-c965-417a-bfec-498a0df54bf1.png)

2022-07-25 23:42 UTC, EduhFarias commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> -    } else {
Ainda é feito a verificação para descartar as alterações feitas? Caso sim, essa parte não pode ser removida

2022-07-25 23:43 UTC, EduhFarias reviewed
Deixei um comentário no `dismiss()`

2022-07-27 03:16 UTC, augustoicaro requested changes

2022-07-27 03:16 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> -    } else {
Eduardo está certo, como esse dialogo é compartilhado com o item de configuração, essa parte ainda é preciso na configuração e deve ser mantida no `dismiss()`

2022-08-02 00:42 UTC, Elygledson commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> -    } else {
verdade

2022-08-02 00:57 UTC, Elygledson commented
Pronto, alterei aquele ponto.

2022-08-04 22:31 UTC, augustoicaro approved these changes

2022-08-04 22:32 UTC, augustoicaro commented
@EduhFarias dá uma olhada aqui e vê se aprova

2022-08-04 22:57 UTC, EduhFarias approved these changes

2022-08-05 00:30 UTC, merged