[NWS-1224][NWS-1710] Change the input label from 'Autor' to 'Gestor' and ...
ninc-management/plataforma pull request #326
Opened 2022-07-24 20:11 UTC by EduhFarias

... make the field editable only for the current contract manager and their AER

Caso em que usuário não é o gestor ou AER responsável:
![1](https://user-images.githubusercontent.com/30202709/180664100-5e8b3dca-bfaf-409b-b035-dfd0fe530402.png)

Caso em que usuário é o atual gestor:
![2](https://user-images.githubusercontent.com/30202709/180664106-ab62dfec-8ce6-4936-9c15-8298453f55df.png)

2022-07-25 23:01 UTC, Elygledson commented
No lugar de autor em "nome de autor"  a palavra gestor deve ser com letra maiúscula mesmo?

2022-07-27 03:20 UTC, augustoicaro commented
> No lugar de autor em "nome de autor" a palavra gestor deve ser com letra maiúscula mesmo?

@Elygledson Não tem muita diferença por ser um placeholder. Mas o correto seria minusculo mesmo

2022-07-27 04:09 UTC, augustoicaro requested changes

2022-07-27 04:09 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +        if (isGranted) this.isInputDisabled$.next(false);
Não entendi essa linha. Do jeito que está essa função hoje ela não server para nada.

2022-08-04 22:35 UTC, augustoicaro approved these changes

2022-08-04 22:36 UTC, merged