[NWS-1552][NWS-1740] Do item/items by object check function (Generic)
ninc-management/plataforma pull request #332
Opened 2022-08-05 00:59 UTC by Elygledson

2022-08-05 21:16 UTC, leo-holanda commented
@Elygledson, quando puder manda um print de como ficou o diálogo dos itens restantes

2022-08-05 21:16 UTC, leo-holanda commented
@Elygledson, quando puder manda por favor um print de como ficou o diálogo dos itens restantes

2022-08-08 13:39 UTC, Elygledson commented
![Screenshot](https://user-images.githubusercontent.com/47836992/183431497-28c98f25-755d-485b-af39-3bd937a4544b.png)

2022-08-08 13:41 UTC, Elygledson commented
![2022-08-08 (1)](https://user-images.githubusercontent.com/47836992/183431957-4255344a-aed7-4636-a9af-a71990a4f74c.png)

2022-08-08 17:36 UTC, leo-holanda requested changes

2022-08-08 17:36 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +enum KEY {
Acho que ficaria melhor com o nome KEYS, já que são múltiplas chaves. Um nome mais sugestivo cairia bem, já que somente KEYS é meio genérico dado o contexto dele. O que tu acha de KEYS_TO_VERIFY?

2022-08-08 17:36 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +              : 'Não é possível remover o item. Os seguintes usuários estão utilizando este cargo',
Não daria pra fazer o ternário só no fim da string do título mudando só a última palavra? Dessa forma evita a repetição da parte do título comum entre os dois

2022-08-08 17:36 UTC, leo-holanda commented on src/app/shared/utils.ts
> +}
Tu acha que daria pra aplicar o conceito de guard clauses aqui? Como é uma "regra" que depende de contexto, não é sempre que é aplicada. Mas acho que nesse cenário cairia bem. Dá uma olhada nesse [link](https://p42.ai/blog/2021-09-29/javascript-refactoring-in-action-replace-nested-if-else-with-guards), tem um exemplo massa de um livro do Martin Fowler

2022-08-08 17:36 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +    const units = getItemsWithValue<Invoice>(this.invoices, key, this.clonedConfig.invoiceConfig.units[i]);
Pelo que vi, o retorno dessa função é um array de objetos do tipo genérico que foi passado como T nos angle brackets. Como o tipo é Invoice, o retorno caindo numa variável chamada units fica meio estranho. invoicesWithUnit ficaria melhor?

Uma dúvida que tive é se seria possível omitir o tipo que é passado entre os angle brackets da mesma forma que ocorreu recentemente numa função que eu tinha feito e que o @augustoicaro deu a dica. Esqueci qual era a função. Mas como a gente já tem o tipo T vindo do primeiro parâmetro, talvez o tipo passado nos angle brackets não seja necessário

2022-08-08 17:36 UTC, leo-holanda commented on src/app/shared/utils.ts
> +      if (typeof obj[keys[0]].find == 'function') {
O instanceof não atenderia esse caso da verificação do array?

2022-08-08 21:35 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +              : 'Não é possível remover o item. Os seguintes usuários estão utilizando este cargo',
feito!

2022-08-08 22:04 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +    const productsWithValue: any = [];
é que neste caso só será uma lista de strings. Eu posso colocar string[] = []

2022-08-08 22:10 UTC, Elygledson commented on src/app/@theme/components/header/config/remaining-items/remaining-items.component.ts
> +  selector: 'remaining-items',
Feito

2022-08-08 22:14 UTC, Elygledson commented on src/app/shared/utils.ts
> +      if (typeof obj[keys[0]].find == 'function') {
neste caso poderíamos usar Array.isArray() que retorna um booleano

2022-08-08 22:51 UTC, Elygledson commented on src/app/@theme/components/header/config/remaining-items/remaining-items.component.ts
> +  @Input() items: any;
Feito

2022-08-08 22:54 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +    const productsWithValue: any = [];
Oxe, é verdade! Me confundi, string[] seria o tipo mesmo

2022-08-08 23:18 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +      .subscribe((users) => (this.users = users));
Feito

2022-08-08 23:20 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +enum KEY {
é fica bom.

2022-08-08 23:27 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +      .subscribe((users) => (this.users = users));
Feito

2022-08-08 23:27 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +    const units = getItemsWithValue<Invoice>(this.invoices, key, this.clonedConfig.invoiceConfig.units[i]);
Feiito

2022-08-08 23:32 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +    const units = getItemsWithValue<Invoice>(this.invoices, key, this.clonedConfig.invoiceConfig.units[i]);
Eita, não entendi. Remover o que está dentro do <>?

2022-08-10 00:39 UTC, leo-holanda requested changes

2022-08-10 00:39 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +  KEY = KEYS_TO_VERIFY;
Também precisa alterar o nome da variável de classe porque no template ela ainda é usada com o nome KEY

2022-08-10 23:08 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  KEY = KEYS_TO_VERIFY;
Feito.

2022-08-10 23:11 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +        invoicesWithUnit.forEach((unit) => {
Feito

2022-08-10 23:12 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +    const units = getItemsWithValue<Invoice>(this.invoices, key, this.clonedConfig.invoiceConfig.units[i]);
Removido

2022-08-11 00:18 UTC, augustoicaro requested changes
Faz a alteração por favor dos pontos que te falei no reunião.

2022-08-12 22:01 UTC, leo-holanda approved these changes
Só um pequeno ponto a mais que não me liguei antes. Mas ficou jóia!

2022-08-12 22:01 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +  deleteUnit(i: number): void {
Seguindo aquela ideia de nomear as variáveis, seria uma boa trocar esse parâmetro das funções de i pra index ou unitIndex só pela sugestividade mesmo.

2022-08-12 22:09 UTC, augustoicaro approved these changes
Só fazer as sugestões do Leo e fechou :)

2022-08-13 16:56 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  deleteUnit(i: number): void {
Troquei.

2022-08-16 23:56 UTC, merged