[NWS-531][NWS-1782]  Person radio button
ninc-management/plataforma pull request #333
Opened 2022-08-13 02:14 UTC by Elygledson

2022-08-13 02:15 UTC, Elygledson commented
![2022-08-12](https://user-images.githubusercontent.com/47836992/184464775-02b800b7-5a04-4ec2-b473-2449eb69dc11.png)

2022-08-15 21:29 UTC, leo-holanda requested changes

2022-08-15 21:29 UTC, leo-holanda commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
> +  selectedOption = 'pessoa física';
Aqui daria pra fazer selectedOption = typeOfPerson.PESSOA_FISICA?

2022-08-15 21:29 UTC, leo-holanda commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
> +enum TypeOfPerson {
Como são dois acho que Types no plural ficaria mais sugestivo

2022-08-15 21:29 UTC, leo-holanda commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            #document="ngModel"
Seria um problema a referência local dos dois inputs ser a mesma (#document) mesmo eles sendo condicionais?

2022-08-15 23:35 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
> +enum TypeOfPerson {
Feito

2022-08-15 23:37 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
> +  selectedOption = 'pessoa física';
Feito

2022-08-15 23:40 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
> +  selectedOption = 'pessoa física';
Feito

2022-08-15 23:40 UTC, Elygledson commented on src/app/shared/validators/contractor-validation.json
>    },
Tu acha que esta repetição é necessário?

2022-08-16 12:40 UTC, leo-holanda commented on src/app/shared/validators/contractor-validation.json
>    },
A de repetir min e maxLength? Rapaz, acho que sim por causa da semântica, já que quando outra pessoa pegar esse código ela teria mais facilidade pra compreender o objetivo dele

2022-08-16 12:41 UTC, leo-holanda approved these changes

2022-08-16 14:46 UTC, Elygledson commented on src/app/shared/validators/contractor-validation.json
>    },
ah, sim

2022-08-16 23:59 UTC, augustoicaro commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            #document="ngModel"
Boa pergunta, acredito que não, pois os 2 nunca iam existir ao mesmo tempo.

2022-08-17 00:04 UTC, augustoicaro requested changes
Só faz essa alteração de ordem por favor

2022-08-17 00:04 UTC, augustoicaro commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +    </div>
Troca esse seletor para vir primeiro do que o documento a ser preenchido. Refletindo aqui no modo que lemos e preenchemos as informações, fazemos isso da esquerda para direita, então se o tipo de input depende desse seletor, devemos preencher ele primeiro.

2022-08-17 23:39 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +    </div>
Feito.

2022-08-17 23:40 UTC, Elygledson commented
![Screenshot (6)](https://user-images.githubusercontent.com/47836992/185262168-2acceb66-14b1-4631-a8f8-9f32869a9437.png)

2022-08-17 23:41 UTC, augustoicaro approved these changes

2022-08-17 23:43 UTC, Elygledson commented
![Screenshot (6)](https://user-images.githubusercontent.com/47836992/185262465-e948cb76-4bd5-4ad3-91ae-b8b415214175.png)

2022-08-17 23:46 UTC, merged