[NWS-531][NWS-1785] Split old address
ninc-management/plataforma pull request #334
Opened 2022-08-15 00:16 UTC by WilamisAviz15

2022-08-15 00:16 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/184560237-c7fbcab4-1f3a-4700-bf98-84907df32bfa.png)
![image](https://user-images.githubusercontent.com/58791888/184560248-4c57efe2-37b6-46ba-8084-57bc89db526a.png)

2022-08-16 21:30 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/184988702-b4049c4b-d3b0-4bda-9637-d0ac1869c082.png)
![image](https://user-images.githubusercontent.com/58791888/184988713-5484ccb2-7c5e-4229-84d6-44ff5e8b9dc3.png)

2022-08-17 23:59 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            caracteres
Tu acha que neste caso seria melhor dizer "números" em vez de caracteres?

2022-08-18 00:00 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            caracteres
Aqui também.

2022-08-18 00:01 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +          </p>
aqui também

2022-08-18 00:04 UTC, Elygledson approved these changes

2022-08-24 00:03 UTC, augustoicaro commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            caracteres
O ponto aqui é que a pontuação da máscara também conta

2022-08-24 00:04 UTC, augustoicaro commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +            caracteres
No caso de nome da rua deveria ser caractres mesmo, ou letras.

2022-08-24 00:13 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei por favor.

2022-08-24 00:13 UTC, augustoicaro commented on src/app/pages/contractors/contractors.component.ts
>            contractor.email.toLowerCase().includes(this.searchQuery.toLowerCase())
Tem que melhorar isso aqui. Esses são os campos buscavéis da versão mobile, então devemos por todos os campos que valha a pena buscar, como cidade, estado, bairro.

2022-08-24 00:13 UTC, augustoicaro commented on src/app/shared/validators/contractor-validation.json
> +      "minLength": 3,
O minimo do zipcode também não deveria ser o máximo e caracteres que pode ter? Assim vamos forçar a sempre ter o zip code com a quantidade de caracteres certas.

2022-08-25 23:10 UTC, WilamisAviz15 commented on src/app/shared/validators/contractor-validation.json
> +      "minLength": 3,
Ajustado.

2022-08-25 23:17 UTC, WilamisAviz15 commented on src/app/pages/contractors/contractors.component.ts
>            contractor.email.toLowerCase().includes(this.searchQuery.toLowerCase())
corrigido

2022-08-25 23:24 UTC, augustoicaro approved these changes

2022-08-25 23:56 UTC, merged