[NWS-531][NWS-1789] add corporate name field (case Pessoa juridica)
ninc-management/plataforma pull request #335
Opened 2022-08-16 01:17 UTC by Elygledson

2022-08-16 01:19 UTC, Elygledson commented
Mobile
![Screenshot (5)](https://user-images.githubusercontent.com/47836992/184777429-cdebd8de-9f85-4863-a631-8f39f52d2846.png)

2022-08-16 14:50 UTC, Elygledson commented on src/app/pages/contractors/contractor-item/contractor-item.component.ts
>      }
Eu fiz esta alteração que eu deveria ter feito na branch base que é para mostrar o input de acordo com o que o usuário preencheu física/jurídica quando abrir um dos cadastros.

2022-08-24 00:24 UTC, augustoicaro requested changes
Revisa aqui esses pontos for favor

2022-08-24 00:24 UTC, augustoicaro commented on src/app/pages/contractors/contractor-item/contractor-item.component.html
> +          <textarea
Razão social deveria ser um input e não uma caixa de texto

2022-08-24 20:00 UTC, EduhFarias approved these changes

2022-08-25 23:25 UTC, Elygledson commented
![Screenshot (9)](https://user-images.githubusercontent.com/47836992/186785985-b2b90f93-8459-4c92-a4d9-ee7a34eef75e.png)
![Screenshot (10)](https://user-images.githubusercontent.com/47836992/186785991-b50e3987-339f-4954-aa6d-65e2a48f6c4e.png)

2022-08-25 23:26 UTC, augustoicaro approved these changes

2022-08-30 00:10 UTC, merged