[NWS-1224][NWS-1796] Investigate promise rejected error in backend
ninc-management/plataforma pull request #342
Opened 2022-08-22 23:47 UTC by Elygledson

Investigate promise rejected error in backend when we update a collection

2022-08-26 23:12 UTC, EduhFarias approved these changes

2022-08-30 22:30 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei.

2022-08-30 22:30 UTC, augustoicaro commented on backend/src/routes/contract.ts
> +      savedContract,
Isso aqui está errado e se repete em todos os arquivos. Lembra que esse cara é um objeto, não podemos ter valor sem chave. Se você ver no passado não mandamos o cara salvo de volta na resposta, apenas a mensagem que ele foi salvo. Pode apagar essa linha de todos.

2022-08-30 22:30 UTC, augustoicaro commented on src/app/pages/pages.component.ts
> +        '<svg viewBox="0 0 547.23 198.39" height="30px"><path style="fill:#212322" d="M154.28 78.16h33.4v117.28h-33.4z"/><path d="M126.91 171.99c-5.29 0-7.72-2.93-7.72-9.53v-41.78c0-8.32 0-45.45-42.9
Defaz a alteração desse arquivo. Um aspa dupla sumiu dessa linha por alguma razão

2022-08-30 23:09 UTC, augustoicaro approved these changes

2022-08-30 23:09 UTC, merged