[NWS-1224][NWS-1818] Investigate issue registering a new promotion
ninc-management/plataforma pull request #344
Opened 2022-08-23 00:28 UTC by Elygledson

Investigate the reason for registering a new message to discard new changes

2022-08-23 00:29 UTC, Elygledson commented
![Recording 2022-08-22 at 21 15 27](https://user-images.githubusercontent.com/47836992/186042615-f30440d9-0c5a-4c79-862c-24501cfa537e.gif)

2022-08-25 22:45 UTC, leo-holanda requested changes
É uma solução que resolve o problema mas não sei se o comportamento de não fechar o diálogo depois de salvar é o que a gente possa querer. Pelo que vi no gif, parece ser um problema que tá relacionado com o tratamento do formDirty. Tu tentou abordar o problema por essa frente?

2022-08-26 00:06 UTC, Elygledson commented
Ainda não @leo-holanda. Vou investigar aqui.

2022-08-26 00:31 UTC, Elygledson commented
![Recording 2022-08-25 at 21 29 52](https://user-images.githubusercontent.com/47836992/186791905-d1f3895c-63fa-4048-8468-afab782b24c3.gif)

2022-08-29 22:36 UTC, leo-holanda approved these changes

2022-08-30 23:38 UTC, augustoicaro approved these changes

2022-08-30 23:40 UTC, merged