[NWS-1171][NWS-1812] Show FAB button on all pages
ninc-management/plataforma pull request #346
Opened 2022-08-24 00:13 UTC by EduhFarias

Exemplo do FAB menu na pág dos clientes:
![oie_azGwTN85eHCm](https://user-images.githubusercontent.com/30202709/186287537-cb669c01-4eee-43ce-9cef-30c8a1dd2b95.png)

2022-08-25 23:37 UTC, WilamisAviz15 approved these changes

2022-09-05 23:45 UTC, augustoicaro requested changes
Dá uma olhada no pontos que levantei e faz o rebase por favor. No rebase faz interativo e tira os 2 primeiros commits, no caso se for pela interface, os 2 de baixo.

2022-09-05 23:45 UTC, augustoicaro commented on src/app/pages/pages.component.ts
> +  NORTAN_EXPENSE_TABLE,
Esse tipo do `NortanExpenseTable` não existe nesse componente. Também é preciso remover esse enun do `dashboard.component.ts`, como lá agora só tem um tipo, dá para simplificar.

2022-09-05 23:45 UTC, augustoicaro commented on src/app/pages/dashboard/dashboard.component.ts
> +    if (dType === DIALOG_TYPES.NORTAN_EXPENSE_TABLE)
Como aqui agora só vai ter um tipo, também não vai precisar mais desse `if`

2022-09-05 23:45 UTC, augustoicaro commented on src/app/pages/pages.component.ts
> +      }
Esse caso não vai acontecer daqui, ou vai?

2022-09-05 23:45 UTC, augustoicaro commented on src/app/pages/pages.component.ts
> +      }
Rever casos que não acontecem mais na nova lista de ações e remover esses tipos do `enum`

2022-09-06 22:28 UTC, augustoicaro requested changes

2022-09-06 22:28 UTC, augustoicaro commented on src/app/pages/dashboard/dashboard.component.ts
>        case DIALOG_TYPES.REPORT_MENU: {
Você também moveu o botão do report, tem que mover esse caso também

2022-09-06 22:28 UTC, augustoicaro commented on src/app/pages/dashboard/dashboard.component.ts
>    REPORT_MENU,
Também precisa mover esse cara para o pages component.

2022-09-09 00:25 UTC, augustoicaro approved these changes

2022-09-09 00:26 UTC, merged