[NWS-1512][NWS-1827] Migrate annual users report generation
ninc-management/plataforma pull request #352
Opened 2022-08-26 00:13 UTC by leo-holanda

![Screenshot from 2022-08-25 21-12-25](https://user-images.githubusercontent.com/26936076/186790375-f7c54639-c943-423e-b1dd-a0799f22d87a.png)

2022-08-31 00:01 UTC, leo-holanda commented
Com botões ocupando a largura do diálogo
![Screenshot from 2022-08-30 21-01-25](https://user-images.githubusercontent.com/26936076/187564264-210e4ba1-796a-45eb-a326-8ce80aab41ab.png)

2022-09-14 03:09 UTC, augustoicaro commented
@leo-holanda vai precisa fazer um rebase desse branch e mudar algumas coisas já que os botões flutuantes mudaram para o `pages.component`. Faz esse ajuste para mim por favor.

2022-09-15 02:50 UTC, Elygledson requested changes

2022-09-15 02:50 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
> +                return getYear(invoice.created) == year && invoice.status != INVOICE_STATOOS.INVALIDADO && typeFilter;
@leo-holanda neste caso aqui não daria para usar operador | ?

2022-09-15 02:50 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
> +      const tmp: IndividualData[] = [];
Fiquei pensando se seria bom declarar este const tmp em algo local já com os valores preenchidos estaticamente. Já que é usado em dois locais .

2022-09-15 02:50 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
> +                  return getYear(contract.created) == year && typeFilter;
@leo-holanda neste caso aqui não daria para usar operador | ?

2022-09-15 23:39 UTC, augustoicaro approved these changes

2022-09-16 00:51 UTC, augustoicaro requested changes

2022-09-16 00:51 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
> +      const tmp: IndividualData[] = [];
o que podemos fazer aqui é definir uma variável `defaultIndividualData` e definir ela como:
```
defaultIndividualData = Array(12).fill({
          received: '0,00',
          expenses: '0,00',
          sent_invoices_manager: 0,
          sent_invoices_team: 0,
          opened_contracts_manager: 0,
          opened_contracts_team: 0,
          concluded_contracts_manager: 0,
          concluded_contracts_team: 0,
        });
```

2022-09-16 00:51 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-users-report/annual-users-report.component.ts
> +      }
mesma coisa aqui

2022-09-20 17:22 UTC, augustoicaro approved these changes

2022-09-20 17:22 UTC, merged