[NWS-1156][NWS-1841] Add OneDrive Folder Setup for Provider Documents
ninc-management/plataforma pull request #359
Opened 2022-09-01 15:07 UTC by Elygledson

2022-09-01 15:09 UTC, Elygledson commented
![Screenshot (11)](https://user-images.githubusercontent.com/47836992/187948770-2f94660d-7b5f-4b89-a2fa-57a9d7367c69.png)

2022-09-08 21:44 UTC, leo-holanda requested changes

2022-09-14 03:41 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei e os do Leo também

2022-09-14 03:41 UTC, augustoicaro commented on backend/src/models/platformConfig.ts
> +  oneDriveId?: string;
Atualmente ele é opcional porque você pode desativar o onedrive. Mas ele sempre poderia ter um valor default de string vazia, ai forçaria no caso do onedrive ativado forçar esse requerimento. @Elygledson segue essa sugestão para os 2 já que você já fez essa restrição na interface.

2022-09-14 03:41 UTC, augustoicaro commented on backend/src/models/platformConfig.ts
>    @prop()
Concordo

2022-09-14 03:41 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.html
> +            (!folderIdOfProviders.value || !oneDriveIdOfProviders.value))
Mais simples que adicionar essa condição diversas vezes seria se aproveitar do form, deixar os campos como requerido e fazer a verificação de valid como fazemos como os outros.

2022-09-20 11:48 UTC, Elygledson commented on backend/src/models/platformConfig.ts
>    @prop()
Feito.

2022-09-20 11:49 UTC, Elygledson commented on backend/src/models/platformConfig.ts
> +  oneDriveId?: string;
Feito.

2022-09-20 19:03 UTC, augustoicaro approved these changes

2022-09-20 19:04 UTC, merged