[NWS-1156][NWS-1833] Possibility of including attachment with description
ninc-management/plataforma pull request #364
Opened 2022-09-16 01:45 UTC by Elygledson

2022-09-19 22:42 UTC, leo-holanda commented
@Elygledson pelo que vi tem algumas alterações desse PR que também tão no #359. Seria bom avaliar pra ver se algumas alterações são mesmo desse PR ou do outro

2022-09-20 20:39 UTC, leo-holanda requested changes
Sei que não foi tu que escolhesse o nome @Elygledson mas eu trocaria de provider pra supplier, talvez em outra task. Acho que é mais próximo de fornecedor e não conflita com o conceito de provider do angular

2022-09-20 20:39 UTC, leo-holanda commented on backend/src/models/shared.ts
> +export class descriptionUploadedFile extends UploadedFile {
Talvez um nome mais sugestivo seja UploadedFileWithDescription. Ou considerar incluir o atributo description na classe UploadedFile mesmo

2022-09-20 20:39 UTC, leo-holanda commented on src/app/shared/services/storage.service.ts
> +              this.onedriveService.oneDriveURI(onedriveFolder) +
Se esse cara é opcional, não deveria ter um tratamento pra quando ele estiver indefinido?

2022-09-20 20:39 UTC, leo-holanda commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                  <nb-list style="width: 100%">
Seria uma boa um print dessa parte

2022-09-21 22:55 UTC, Elygledson commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                  <nb-list style="width: 100%">
![2022-09-21](https://user-images.githubusercontent.com/47836992/191624394-93c6b591-d223-4f58-b52c-d9034aa0ac8b.png)

2022-09-21 22:56 UTC, Elygledson commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                  <nb-list style="width: 100%">
![2022-09-21 (1)](https://user-images.githubusercontent.com/47836992/191624536-fe2d51a2-be07-4233-a665-adba39c4a522.png)

2022-09-21 22:59 UTC, Elygledson commented on src/app/shared/services/storage.service.ts
> +              this.onedriveService.oneDriveURI(onedriveFolder) +
eu deixei assim porque lá na função oneDriveURI no serviço tem um default, caso ele não passe nada eu espero que ele queira usar a URI de contracts

2022-09-21 23:03 UTC, Elygledson commented on backend/src/models/shared.ts
> +export class descriptionUploadedFile extends UploadedFile {
ah, feito.

2022-09-22 21:34 UTC, augustoicaro commented on src/app/shared/services/storage.service.ts
> +              this.onedriveService.oneDriveURI(onedriveFolder) +
Então, o argumento da função `oneDriveURI` não é opcional, ele é requerido e tem um valor padrão. Caso não seja passado nenhum valor ele vai assumir o valor padrão, então não precisar tratar o caso de indefinido.

2022-09-22 21:59 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei aqui e reponde as perguntas que fiz.

2022-09-22 21:59 UTC, augustoicaro commented on src/app/@theme/components/file-uploader/file-uploader.component.ts
> +import { OneDriveFolders } from 'app/shared/services/onedrive.service';
Para que esse import aqui? Você importou e não usou em nenhum canto

2022-09-22 21:59 UTC, augustoicaro commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.ts
> +      return 'documento' + extension;
Lhe falei isso diversas vezes. Aqui você está salvando o arquivo sempre com o mesmo nome, assim ele vai reescrever o arquivo toda vez que você upar um aquivo novo, você chegou a testar isso?

2022-09-22 21:59 UTC, augustoicaro commented on src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.ts
> +      this.uploadedFiles = cloneDeep(this.expense.uploadedFiles) as UploadedFileWithDescription[];
Por que você trocou o tipo aqui dos arquivos upados da despesa de time?

2022-09-22 21:59 UTC, augustoicaro commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                  <nb-list style="width: 100%">
Esse diff fica estanho quando não ativa aquela opção do espaço, mas depois de ativar fica tudo mais claro

2022-09-23 22:29 UTC, Elygledson commented on src/app/@theme/components/file-uploader/file-uploader.component.ts
> +import { OneDriveFolders } from 'app/shared/services/onedrive.service';
Achei que deixei passar quando estava resolvendo conflitos. Vou reverificar e corrigir

2022-09-23 23:14 UTC, Elygledson commented on src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.ts
> +      this.uploadedFiles = cloneDeep(this.expense.uploadedFiles) as UploadedFileWithDescription[];
Ah Augusto é porque este componente TeamExpenseItemComponent herda do baseExpenseComponent que por sua vez herda do OneDriveDocumentUploader e nesta class eu declarei o uploadedFiles do tipo UploadedFileWithDescription.

2022-09-23 23:40 UTC, Elygledson commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                  <nb-list style="width: 100%">
Eita Augusto não entendi muito bem. Mas eu achei estranho também a versão mobile caso seja isto.

2022-09-23 23:45 UTC, Elygledson commented on src/app/@theme/components/file-uploader/file-uploader.component.ts
> +import { OneDriveFolders } from 'app/shared/services/onedrive.service';
É realmente não tinha utilidade.

2022-09-26 23:16 UTC, augustoicaro commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.ts
> +      return 'documento' + extension;
Ah, bacana! Eu me lembro que tinha uma configuração assim, faz um favor então, adiciona um comentário sobre isso acima da linha 88. Dizendo que a política do onedrive incrementa arquivos com mesmo nome.

2022-09-26 23:40 UTC, augustoicaro commented on src/app/shared/components/teams/team-expenses/team-expense-item/team-expense-item.component.ts
> +      this.uploadedFiles = cloneDeep(this.expense.uploadedFiles) as UploadedFileWithDescription[];
Hum, entendi. Mas temos um problema aqui do description não ser opcional e não ter um código no playground para tratar esse casa nas despesas do time. Estou achando que essa decisão de unificar tudo no `OneDriveDocumentUploader` não foi tão boa assim. No caso das despesas de time essa descrição ser sempre vazia é algo bem estranho.

Talvez se esse cara for um `Union` dos 2 tipos faça mais sentido. Aí mantem `UploadedFile` para as despesas de time.

2022-09-30 18:19 UTC, leo-holanda approved these changes
O union de tipos funciona mas eu acredito que seria mais interessante incluir o campo de descrição no UploadedFile e quem não utilizar ele seria vazio mesmo. Como é um atributo só, não é um custo muito grande ter uploads com um campo de string vazia e não seria necessária a inclusão do tratamento do union.

2022-10-03 22:24 UTC, augustoicaro commented
> O union de tipos funciona mas eu acredito que seria mais interessante incluir o campo de descrição no UploadedFile e quem não utilizar ele seria vazio mesmo. Como é um atributo só, não é um custo muito grande ter uploads com um campo de string vazia e não seria necessária a inclusão do tratamento do union.

Essa seria uma solução de contorno. De fato pensamos em fazer assim, que no fim fazia mais sentido ter apenas um tipo. Mas de fato temos 2 abstrações distintas que são armazenadas em locais distintos. Assim não faz sentido salvarmos um objeto que nunca vai ter descrição com um membro de descrição vazio. Concordo com você que simplificaria, mas para essa isso fazer sentido tinha trocar um pouco as coisas. Por exemplo, a classe base seria a classe com a descrição e a classe sem, ia estender da classe com descrição inicializando ela como string vazia.

2022-10-03 22:26 UTC, augustoicaro approved these changes

2022-10-04 00:53 UTC, Elygledson commented
@augustoicaro feito!

2022-10-04 22:31 UTC, merged