[NWS-1156][NWS-1834] If legal entity can add contacts, which can be vendors, directors, etc. (name, title, email, number)
ninc-management/plataforma pull request #367
Opened 2022-09-27 22:55 UTC by Elygledson

2022-09-28 11:45 UTC, Elygledson commented
![Recording 2022-09-28 at 08 30 48](https://user-images.githubusercontent.com/47836992/192768466-2cad6e2e-0e8e-403d-8fd3-7cefce2e02c5.gif)

Eu notei aqui que a foto e o conteúdo não ficam lado a lado de modo correto entre o intervalo min-width: 767px e max-width: 1023px. Ai fiquei pensando em aumentar o tamanho do nb-card. O que acham?

2022-09-30 18:41 UTC, leo-holanda requested changes

2022-09-30 18:41 UTC, leo-holanda commented on backend/src/models/provider.ts
> +  contact: Contact[] = [];
Como é um array, seria interessante o nome ser contacts

2022-09-30 18:45 UTC, leo-holanda commented
Essa do espaço em branco eu não me lembro de ter visto até então. Vou dar checkout nesse branch depois pra ver com mais detalhes

2022-09-30 18:46 UTC, leo-holanda reviewed
Outro ponto que esqueci @Elygledson. É possível editar um contato?

2022-09-30 23:29 UTC, Elygledson commented
@leo-holanda no momento não temos como atualizar os contatos

2022-09-30 23:33 UTC, Elygledson commented
@augustoicaro eu fiz uma mudança visual apenas no meu local para vocês darem uma olhada. Aumentei o tamanho do dialog de col-md-8 para col-md-10. Vocês acham que ficou bom?
![Recording 2022-09-30 at 20 27 46-min](https://user-images.githubusercontent.com/47836992/193369267-9971ad51-ebfd-4af2-9cb7-9fd8fd67fa1a.gif)

2022-10-01 10:05 UTC, Elygledson commented on backend/src/models/provider.ts
> +  contact: Contact[] = [];
Verdade. Vou trocar.

2022-10-03 22:47 UTC, augustoicaro commented
Não consegui ver no gif esse problema do branco que você disse. Sobre a tooltip no celular ela aparece sim, só não é como no pc que temos que colocar o mouse por cima e aparece. tem que tocar no input.

2022-10-06 00:38 UTC, Elygledson commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
>                    nbButton
Rapaz pessoal eu tive que usar o margin-top mesmo porque não consegui descobrir porque ele não tá criando espaço entre o botão e a div acima

2022-10-07 22:53 UTC, augustoicaro approved these changes

2022-10-07 22:54 UTC, augustoicaro commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
>                    nbButton
Acho que o row ou o form group que dá o espaçamento na verdade. nesse caso precisa usar o margin-top mesmo

2022-10-10 22:25 UTC, leo-holanda approved these changes

2022-10-12 23:03 UTC, merged