[NWS-1156][NWS-1836] Add provider information to invoice
ninc-management/plataforma pull request #368
Opened 2022-09-28 01:38 UTC by EduhFarias

Campo para adicionar fornecedor no orçamento:
![Captura de tela de 2022-09-27 22-11-45](https://user-images.githubusercontent.com/30202709/192667654-68983c19-9247-413c-9180-6b3b0e19dce9.png)

Visualização do fornecedor no pdf do orçamento:
![Captura de tela de 2022-09-27 22-12-10](https://user-images.githubusercontent.com/30202709/192667659-321b6b59-30fa-4fe5-8468-ef2ab8e02567.png)

2022-09-28 01:39 UTC, EduhFarias commented
Ainda não fiz alteração no banco, vou ficar no aguardo caso algo precise ser alterado

2022-09-30 18:02 UTC, leo-holanda requested changes
Só alguns pontos pequenos

2022-09-30 18:02 UTC, leo-holanda commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                      caracteres
A mensagem de erro permaneceu para um campo de endereço

2022-09-30 18:02 UTC, leo-holanda commented on src/app/shared/services/provider.service.ts
> +    list: (Provider | string | undefined)[] //AER
Talvez não precise do comentário //AER aqui

2022-09-30 18:04 UTC, leo-holanda commented
Rapaz, eu vi a notificação e pensei que era review pra mim mas não era kkkk

2022-10-03 22:45 UTC, Elygledson commented on src/app/pages/invoices/pdf.service.ts
> +      pdf.add(pdf.ln(1));
seria melhor remover os comentários?

2022-10-03 22:53 UTC, Elygledson commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                      caracteres
A  mensagem de erro não está de acordo com o objetivo do input que é escrever uma descrição para o fornecedor.

2022-10-03 22:53 UTC, Elygledson commented on src/app/shared/services/provider.service.ts
> +    list: (Provider | string | undefined)[] //AER
Concordo.

2022-10-05 22:13 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei

2022-10-05 22:13 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.html
> +                disabled
trocar por `readonly` para não deixar cinza e dificultar a leitura das informações

2022-10-05 22:13 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
> +
Não precisa desse texto da lista de forncedores, seria tudo como se fosse uma lista só. Desse bloco de código só ficaria o `if`

2022-10-05 22:13 UTC, augustoicaro commented on src/app/shared/services/provider.service.ts
> +    list: (Provider | string | undefined)[] //AER
Concordo

2022-10-05 22:13 UTC, augustoicaro commented on src/app/pages/providers/provider-item/provider-item/provider-item.component.html
> +                      caracteres
Concordo com alteração

2022-10-07 23:05 UTC, augustoicaro approved these changes

2022-10-12 19:52 UTC, leo-holanda approved these changes

2022-10-12 23:55 UTC, merged