[NWS-1864][NWS-1883] Add logo upload
ninc-management/plataforma pull request #373
Opened 2022-10-05 19:45 UTC by leo-holanda

![Screenshot from 2022-10-05 16-44-47](https://user-images.githubusercontent.com/26936076/194148825-6457881d-01b4-4324-8356-f28f48a24936.png)

2022-10-12 22:40 UTC, Elygledson approved these changes

2022-10-12 22:41 UTC, Elygledson commented
@leo-holanda depois tu poderia mostrar a versão mobile?

2022-10-12 22:50 UTC, leo-holanda commented on src/app/pages/invoices/pdf.service.ts
>        margin: [5, 20, 5, 5],
Isso! Não me aprofundei muito nas motivações mas é que somente a URL dela não basta pra aparecer no PDF. Aí precisa criar esse objeto

2022-10-13 00:16 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
>        margin: [5, 20, 5, 5],
Sim, acreduto que na bibliotca angular que usamos deve ter uma forma simplificada de fazer

2022-10-17 21:20 UTC, leo-holanda commented
> @leo-holanda depois tu poderia mostrar a versão mobile?

Eu verifiquei a versão mobile aqui @Elygledson e ela tá meio estranha.

![Screenshot from 2022-10-17 18-19-43](https://user-images.githubusercontent.com/26936076/196285682-5ce6d728-adf2-4dac-8b63-f55fef040d74.png)

Vou fazer algumas alterações e mando uma versão corrigida

2022-10-17 23:46 UTC, leo-holanda commented
@Elygledson 
![Screenshot from 2022-10-17 20-46-22](https://user-images.githubusercontent.com/26936076/196303830-73d24640-8d21-40f6-8d8e-49946c565b21.png)

2022-10-26 21:12 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei por favor.

2022-10-26 21:12 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +              return this.config.socialConfig.companyName.toLowerCase() + '_' + this.translateLogoType(logoType);
Colocar um TODO aqui para trocarmos o nome pelo ID da empresa, vai ficar melhor assim.

2022-10-26 21:12 UTC, augustoicaro commented on src/app/auth/auth.component.ts
> +  }
Aqui no login/cadastro não precisamos da logo da empresa, será tudo NINC. A priori não devemos fazer nenhum requisição para o servidor sem o usuário estar logado para não facilitar pegar a chave de autenticação das APIs

2022-10-27 00:24 UTC, augustoicaro approved these changes

2022-10-27 00:24 UTC, merged