[NWS-1901][NWS-1905] Create model for Enterprise
ninc-management/plataforma pull request #382
Opened 2022-10-27 18:30 UTC by Elygledson

2022-10-31 21:09 UTC, leo-holanda requested changes

2022-10-31 21:09 UTC, leo-holanda commented on playground.mongodb
> +  const savedCompany = await db.companys.insertOne(config.socialConfig);
O nome da coleção era companys mesmo ou companies nesse caso?

2022-10-31 21:09 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +  disable(): boolean {
O que tu acha de renomear a função pra isDisabled? ou algo como shouldDisableCompanyInput

2022-10-31 21:09 UTC, leo-holanda commented on src/app/public/public.component.html
> +          <span *ngIf="config.company && companyService.idToCompany(config.company).showCompanyName">{{  companyService.idToCompany(config.company).companyName }}</span>
Uma alternativa seria substituir o uso do idToCompany no template por uma variável de classe que seria preenchida no ngOnInit. Talvez simplificasse mas é uma alternativa apenas, dessa forma também funciona

2022-11-01 23:09 UTC, Elygledson commented on src/app/public/public.component.html
> +          <span *ngIf="config.company && companyService.idToCompany(config.company).showCompanyName">{{  companyService.idToCompany(config.company).companyName }}</span>
Feito!

2022-11-01 23:10 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  disable(): boolean {
Eu exclui. Eu fiz o que tu pediu abaixo.

2022-11-07 19:49 UTC, leo-holanda requested changes

2022-11-07 19:49 UTC, leo-holanda commented on src/app/@theme/components/footer/footer.component.ts
> +      .subscribe(([, , config, _]) => {
Se não me engano, nesse cenário pode omitir o _ e deixar no lugar um espaço em branco

2022-11-07 19:49 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +  checkLogo(logoType: LOGO_TYPES): UploadedFile {
Talvez não precisasse dessa função já que por conta da função verifyEmptyLogos a gente sabe que mesmo se vier vazio do banco a gente preenche localmente. Acredito que entraria sempre no primeiro if

2022-11-07 19:49 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.ts
> +                ).toLowerCase() +
Aqui não daria pra usar o this.company ou this.clonedCompany mesmo?

2022-11-07 21:57 UTC, augustoicaro commented on src/app/@theme/components/footer/footer.component.ts
> +      .subscribe(([, , config, _]) => {
Verdade eu vi isso quando ele me mostrou uma vez, mas não tive a chance de comentar sobre

2022-11-09 21:23 UTC, Elygledson commented on src/app/@theme/components/footer/footer.component.ts
> +      .subscribe(([, , config, _]) => {
feito!

2022-11-09 21:27 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +                ).toLowerCase() +
Feito!

2022-11-09 21:44 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +  checkLogo(logoType: LOGO_TYPES): UploadedFile {
Leo eu fiz o teste sem chamar a função para verificar

2022-11-16 22:33 UTC, augustoicaro requested changes
Levantei o ponto aqui para pequenas correções, mas no geral está muito bom o trabalho foi só falta de atenção em alguns pontos. @leo-holanda re-revisa novamente esse aqui para fecharmos esse merge.

2022-11-16 22:33 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +  checkLogo(logoType: LOGO_TYPES): UploadedFile {
Não entendi bem. Mas acho que o ponto que o Leo levantou é veificar se está sempre entrando nesse if. Se sempre entrar nesse if não ia precisar da função. Verifica isso por favor

2022-11-16 22:33 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +          this.company[logoType] = uploadedLogo;
Por que aqui estamos usando o `this.company` e não o `this.clonedCompany`?

2022-11-16 22:33 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +        this.company[logoType].url =
Mesma coisa do `this.clonedCompany` aqui

2022-11-16 22:33 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.ts
> +      .subscribe(([currentUser, , , config]) => {
Essa captura aqui está errada. Você tem 5 argumentos e só está tratando 4. `[1, 2, 3, 4]`, faltou uma vírgula a mais

2022-11-16 22:33 UTC, augustoicaro commented on src/app/pages/pages.component.ts
> +      .subscribe(([_, , , configs, teams, , isGranted]) => {
Não recisa desse `_` no inicio

2022-11-17 18:44 UTC, leo-holanda requested changes

2022-11-17 18:44 UTC, leo-holanda commented on src/app/@theme/components/header/config/config.component.html
> +                  [(ngModel)]="checkLogo(LOGO_TYPES.logoDefault).name"
Eu verifiquei aqui esse ponto do checkLogo, Elygledson. De fato, não precisa da função. Dessa forma abaixo, ele acessa a logo. Aí basta trocar de name pra url onde a url for acessada e trocar o tipo da logo pra cada input respectivo ao tipo

`[(ngModel)]="company[LOGO_TYPES.logoDefault].name"`

2022-11-17 19:50 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +                  [(ngModel)]="checkLogo(LOGO_TYPES.logoDefault).name"
Feito!

2022-11-17 19:51 UTC, Elygledson commented on src/app/pages/pages.component.ts
> +      .subscribe(([_, , , configs, teams, , isGranted]) => {
Removido!

2022-11-17 19:53 UTC, Elygledson commented on src/app/@theme/components/header/header.component.ts
> +      .subscribe(([currentUser, , , config]) => {
Prettier ao salvar está removendo. Estranho.

2022-11-17 20:06 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +        this.company[logoType].url =
Feito!

2022-11-17 20:06 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.ts
> +          this.company[logoType] = uploadedLogo;
Feito!

2022-11-17 22:46 UTC, leo-holanda approved these changes

2022-11-23 22:21 UTC, augustoicaro commented on src/app/@theme/components/header/config/config.component.ts
> +    this.clonedCompany = cloneDeep(this.company);
Não entendi essa parte aqui. Para que ser o `this.company`?

2022-11-26 00:10 UTC, augustoicaro approved these changes

2022-11-29 23:26 UTC, merged