[NWS-1866][NWS-1913] Make invoice pdf reactive to configs
ninc-management/plataforma pull request #383
Opened 2022-11-01 13:40 UTC by leo-holanda

Exemplo de PDF: [ORC-40_2022-TNT_NINC (18).pdf](https://github.com/ninc-management/plataforma/files/9910353/ORC-40_2022-TNT_NINC.18.pdf)

2022-11-03 23:47 UTC, Elygledson approved these changes

2022-11-07 22:00 UTC, augustoicaro commented
@leo-holanda faz um rebase por favor com -i para o main removendo os commits que já entraram. Dei vacilo e não vi que o commit que fiz merge era a base desse PR

2022-11-08 00:36 UTC, augustoicaro requested changes
Como discutido no encontro técnico, vamos precisar adicionar uma configuração extra na configuração do orçamento para configurar a cor da fonte para os retângulos de importante (preto e branco) e um toggle para marcar se a fonte será em negrito.

Outro ponto, a cor do retângulo de importante deve seguir um tom mais claro da cor principal (400 ou 300) e (600 ou 700) no retângulo mais escuro.

2022-11-17 22:27 UTC, augustoicaro approved these changes

2022-11-17 22:27 UTC, merged