[NINC-699][NINC-704] Authentication service
ninc-management/plataforma pull request #388
Opened 2022-11-11 00:49 UTC by Elygledson

2022-11-17 18:50 UTC, leo-holanda approved these changes

2022-11-25 22:21 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei.

2022-11-25 22:21 UTC, augustoicaro commented on src/app/auth/auth.service.spec.ts
> +  it('isUserRegistred should work', (done: DoneFn) => {
Faltou fazr o testes em que ele passa

2022-11-25 22:21 UTC, augustoicaro commented on src/app/auth/auth.service.spec.ts
> +  it('isUserProspect should work', (done: DoneFn) => {
Também faltou fazer o teste em que ele passa

2022-11-25 22:21 UTC, augustoicaro commented on src/app/auth/auth.service.spec.ts
> +  it('isUserActive should work', (done: DoneFn) => {
Também faltou fazer o teste o que ele, passa. Em especial esse aqui tem que fazer um teste extra para um usuario presente no banco, mas não está ativo.

2022-11-30 00:50 UTC, Elygledson commented on src/app/auth/auth.service.spec.ts
> +    expect(service.userEmail()).toBe('user');
Feito!

2022-11-30 00:50 UTC, Elygledson commented on src/app/auth/auth.service.spec.ts
> +  it('isUserRegistred should work', (done: DoneFn) => {
Feito!

2022-11-30 00:50 UTC, Elygledson commented on src/app/auth/auth.service.spec.ts
> +  it('isUserProspect should work', (done: DoneFn) => {
Feito!

2022-11-30 00:50 UTC, Elygledson commented on src/app/auth/auth.service.spec.ts
> +  it('isUserActive should work', (done: DoneFn) => {
Feito!

2022-12-15 23:54 UTC, augustoicaro approved these changes

2022-12-15 23:55 UTC, merged