[NINC-1169][NINC-1879] Create dialog for adding editing justification
ninc-management/plataforma pull request #395
Opened 2022-11-24 22:52 UTC by Elygledson

2022-11-24 22:53 UTC, Elygledson commented
![Uploading Recording 2022-11-24 at 19.12.44.gif…]()

2022-11-24 22:54 UTC, Elygledson commented
![Recording 2022-11-24 at 19 12 44](https://user-images.githubusercontent.com/47836992/203871938-38f3959d-b181-4ce7-8579-970233f2bb14.gif)

2022-11-24 23:44 UTC, leo-holanda requested changes

2022-11-24 23:44 UTC, leo-holanda commented on src/app/shared/components/edition-dialog/edition-dialog.component.ts
> +    this.latestEdition.author = this.transaction.author;
Nesse caso não deveria ser o usuário corrente não? Não sei se existe a possibilidade de alguém que não seja o autor editar uma transação

2022-11-24 23:44 UTC, leo-holanda commented on src/app/shared/components/edition-dialog/edition-dialog.component.html
> +            #editionHistory="ngModel"
Talvez newEdition seja um nome mais intuitivo. O que tu acha?

2022-11-24 23:44 UTC, leo-holanda commented on src/app/shared/components/transactions/transaction-item/transaction-item.component.ts
> +              this.team.transactions.push(saveTransactionResponse.transaction._id);
No caso, por estar editando uma transação, seria necessário adicionar a referência dela no array depois dela ter sivo salva? Porque dá a impressão de estar duplicando a referência por ela já existir e ter sido acessada pra a edição acontecer

2022-11-25 22:46 UTC, Elygledson commented on src/app/shared/components/edition-dialog/edition-dialog.component.html
> +            #editionHistory="ngModel"
verdade.

2022-11-25 23:04 UTC, Elygledson commented on src/app/shared/components/transactions/transaction-item/transaction-item.component.ts
> +              this.team.transactions.push(saveTransactionResponse.transaction._id);
Ah, Leo! Na verdade, eu devereria ter usado a função edit do serviço de transação

2022-11-29 14:34 UTC, leo-holanda approved these changes
Ficou massa essa simplificação com o newComment. Se não me engano tem um componente chamado text-input-dialog que faz algo parecido. De repente, não seria necessário o edition-dialog pelo text-input-dialog fazer um trabalho semelhante. Seria uma boa considerar.

2022-12-16 22:24 UTC, augustoicaro approved these changes

2022-12-16 22:24 UTC, merged