[NINC-1169][NINC-1953]Create dialog for change history list
ninc-management/plataforma pull request #400
Opened 2022-12-14 01:32 UTC by Elygledson

2022-12-14 01:33 UTC, Elygledson commented
![2022-12-13](https://user-images.githubusercontent.com/47836992/207483051-014f8ea8-191d-4444-981b-ad1182e01b8c.png)

2022-12-14 01:40 UTC, Elygledson commented
![2022-12-13 22 39 39 4200-nincmanageme-plataforma-ldj414z5h5k ws-us79 gitpod io 2dd16065474a](https://user-images.githubusercontent.com/47836992/207483960-c4539d7d-bdea-46ae-bbef-6d24cef4e13d.png)

2023-01-06 00:26 UTC, augustoicaro requested changes

2023-01-06 00:26 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +          this.detector.markForCheck();
Talvez não precise dessa parte se o refactoring de remoção da estratégia de atualização do contract-item for para frente.

2023-01-06 00:26 UTC, augustoicaro commented on src/app/shared/components/text-input-dialog/text-input-dialog.component.ts
> +  @Input() buttonProperties = {
Esse nome aqui não ficou bom, seria melhor usar `dialogProperties`

2023-01-06 20:36 UTC, Elygledson commented on src/app/shared/components/text-input-dialog/text-input-dialog.component.ts
> +  @Input() buttonProperties = {
Feito!

2023-01-06 22:49 UTC, merged