[NINC-1902][NINC-1909] Make interceptor to pass the logged in user's company ID on all requests
ninc-management/plataforma pull request #411
Opened 2023-01-31 22:23 UTC by Elygledson

2023-02-01 23:29 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei.

2023-02-01 23:29 UTC, augustoicaro commented on src/app/shared/interceptors/api-auth.service.ts
> +    });
Construtor precisa ser async e esperar que o usuario corrente esteja definido para continuar.

2023-02-01 23:29 UTC, augustoicaro commented on src/app/shared/interceptors/api-auth.service.ts
> +import { conns } from '../../../../backend/src/shared/global';
Essa linha não está sendo usada, por favor remover.

2023-02-10 21:34 UTC, Elygledson commented on src/app/shared/interceptors/api-auth.service.ts
> +import { conns } from '../../../../backend/src/shared/global';
Feito!

2023-02-24 23:03 UTC, augustoicaro approved these changes
Tudo certo, só ficou fazendo fazer o teste da função nova que você criou no serviço de autenticação.

2023-02-27 23:41 UTC, merged