[NINC-1902][NINC-1979]  change company model to save userless connection URI and password
ninc-management/plataforma pull request #413
Opened 2023-02-03 21:36 UTC by Elygledson

2023-02-10 21:32 UTC, augustoicaro requested changes
Vê esse ponto que levantei. Uma coisa que não vi é onde que você está usando essa função do `uri`?

2023-02-10 21:32 UTC, augustoicaro commented on backend/src/shared/util.ts
> +export function __uri(company: Company): string {
O nome não precisa ter `__`. Por convenção isso representa algo que você quer encapsular/escoder. Como essa é uma função pública não tem sentido ter esses underlines

2023-02-10 23:27 UTC, Elygledson commented on backend/src/shared/util.ts
> +export function __uri(company: Company): string {
Feito!

2023-02-14 21:43 UTC, augustoicaro approved these changes

2023-02-14 21:44 UTC, merged