[NINC-1902][NINC-1980] Make connection map and helper function that given a company ID returns or creates a connection
ninc-management/plataforma pull request #414
Opened 2023-02-25 02:28 UTC by Elygledson

…ns or creates a connection

2023-02-25 02:32 UTC, Elygledson commented on backend/src/shared/util.ts
> -
Eu removi por achar que faz mais sentido fazer isto na função de criar. Mas qualquer coisa desfaço.

2023-02-25 02:34 UTC, Elygledson commented on backend/src/routes/invoice.ts
>    return res.status(200).json(Array.from(Object.values(invoicesMap)));
@augustoicaro fiquei pensando se este Array.from é necessário já que Object.values retorna um array 🤔

2023-02-28 23:54 UTC, augustoicaro commented
Faz o rebase interativo para o main e deixa somente os 2 ultimos commits. Tem coisa que não precisa aqui.

2023-03-01 06:22 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que falei aqui.

2023-03-01 06:22 UTC, augustoicaro commented on backend/src/shared/util.ts
> -
Faz sentido sim. Só vamos precisar de fato montar a URI para fazer essa conexão.

2023-03-01 06:22 UTC, augustoicaro commented on backend/src/routes/invoice.ts
> +
Esse arquivo não deveria estar nesse PR. E essas duas funções já foram removidas na nossa última conversa. Generalizamos uma e a outra simplificamos ela deixando direto na linha que era chamada.

2023-03-01 12:57 UTC, Elygledson commented on backend/src/routes/invoice.ts
> +
Feito!

2023-03-01 23:30 UTC, augustoicaro approved these changes

2023-03-01 23:31 UTC, merged