[NINC-1902][NINC-2034] Add company DB handling to the team route
ninc-management/plataforma pull request #419
Opened 2023-03-03 20:31 UTC by Elygledson

2023-03-07 23:12 UTC, augustoicaro requested changes
Atualiza o teu branch e faz essa alteração que pedi por favor.

2023-03-07 23:12 UTC, augustoicaro commented on backend/src/routes/team.ts
>        });
Não se deve misturar `await` com `then`, isso aqui já era um bug. Deixa assim:
```ts
const team = await teamCompanyModel.findOne({ _id: req.body.team._id });
newExpense.code = '#' + team.expenses.length.toString();
team.expenses.push(newExpense);
req.body.team.expenses = cloneDeep(team.expenses);
```

2023-03-08 00:48 UTC, Elygledson commented on backend/src/routes/team.ts
>        });
@augustoicaro Feito!

2023-03-08 01:06 UTC, Elygledson commented on backend/src/shared/global.ts
> -import { Contractor } from '../models/contractor';
removi o import do contractor que entrou na 1902. Não tinha visto

2023-03-13 23:18 UTC, augustoicaro approved these changes

2023-03-13 23:20 UTC, merged