[NINC-1902][NINC-2040] Add company DB handling to the company route
ninc-management/plataforma pull request #421
Opened 2023-03-03 21:35 UTC by Elygledson

2023-03-15 23:09 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei

2023-03-15 23:09 UTC, augustoicaro commented on backend/src/routes/company.ts
> +    const company = new companyModel(req.body.company);
O campany vai ser sempre salvo no banco principal, precisando somente fazer:
```ts
const company = new CompanyModel(req.body.company);
```

2023-03-15 23:09 UTC, augustoicaro commented on backend/src/routes/company.ts
> +    const companies: Company[] = await companyModel.find({});
Mesma coisa aqui

2023-03-15 23:09 UTC, augustoicaro commented on backend/src/routes/company.ts
> +    await companyModel.findByIdAndUpdate(req.body.company._id, req.body.company, {
Mesma coisa aqui

2023-04-04 22:23 UTC, Elygledson commented on backend/src/routes/company.ts
> +    await companyModel.findByIdAndUpdate(req.body.company._id, req.body.company, {
Eu retornei ao que era ontem.

2023-04-04 22:23 UTC, Elygledson commented on backend/src/routes/company.ts
> +    const companies: Company[] = await companyModel.find({});
Eu retornei ao que era ontem.

2023-04-04 22:23 UTC, Elygledson commented on backend/src/routes/company.ts
> +    const company = new companyModel(req.body.company);
Eu retornei ao que era ontem.

2023-04-17 21:18 UTC, augustoicaro approved these changes

2023-04-17 21:25 UTC, merged