[NINC-1902][NINC-2037] Add company DB handling to the config route
ninc-management/plataforma pull request #427
Opened 2023-03-08 18:34 UTC by Elygledson

2023-03-08 18:43 UTC, Elygledson commented on backend/src/shared/util.ts
> +export async function getPermissionsFromNotificationConfig(companyId: string, notificationTag: string): Promise<any> {
Fiquei na dúvida se foi uma boa escolha fazer estas alterações nesta função

2023-03-08 18:47 UTC, Elygledson commented on backend/src/routes/notification.ts
>  }
Como alterei isNotificationEnabled tive que fazer algumas alterações aqui importantes.

2023-03-08 18:47 UTC, Elygledson commented on backend/src/routes/notification.ts
>  }
E consequentemente apaguei o subject

2023-04-17 21:33 UTC, augustoicaro requested changes

2023-04-30 19:16 UTC, augustoicaro approved these changes

2023-04-30 19:17 UTC, merged