[NINC-2028][NINC-2071] Review course component
ninc-management/plataforma pull request #450
Opened 2023-04-06 23:09 UTC by Elygledson

2023-04-08 19:13 UTC, augustoicaro requested changes

2023-04-08 19:13 UTC, augustoicaro commented on src/app/pages/courses/courses.component.ts
> -        this.courses = courses.map((course: Course) => {
Que fim levou o `this.courses`?

2023-04-08 19:13 UTC, augustoicaro commented on src/app/pages/courses/courses.component.ts
> +        valuePrepareFunction: (participants: CourseParticipant[]): string => participants.length.toString(),
Aqui como usamos o `valuePrepareFunction`, temos que também fazer uma função para o filtro e sort. Verifica que se ambas as funções de filtro e sort estão funcionando na tabela, se não é preciso implementar essas funções.

2023-04-10 22:47 UTC, Elygledson commented on src/app/pages/courses/courses.component.ts
> -        this.courses = courses.map((course: Course) => {
Verdade. Desfiz a alteração.

2023-05-03 00:36 UTC, augustoicaro requested changes
Só ficou faltando esse detalhe aqui para fechar

2023-05-03 00:36 UTC, augustoicaro commented on src/app/pages/courses/courses.component.ts
> +        },
faltou a função de sort aqui

2023-05-04 21:34 UTC, Elygledson commented on src/app/pages/courses/courses.component.ts
> +        },
Este aqui já está ordenando

2023-05-20 18:16 UTC, augustoicaro commented on src/app/pages/courses/courses.component.ts
> +        },
Esse é um bom ponto de atenção. O array já está ordenado é diferente da tabela saber como ordenar caso clique na coluna e mude a ordenação entre crescente/decrescente. Se a tabela não sabe como ordenar essa funcionalidade não irá funcionar. Ajustei aqui.

2023-05-20 18:48 UTC, augustoicaro approved these changes

2023-05-20 18:53 UTC, merged