[NINC-2028][NINC-2074] Review invoice component
ninc-management/plataforma pull request #457
Opened 2023-04-17 20:42 UTC by Elygledson

2023-05-03 02:51 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei aqui.

2023-05-03 02:51 UTC, augustoicaro commented on src/app/pages/invoices/invoices.component.ts
> +        valuePrepareFunction: (author: Ref<User>) => (author ? this.userService.idToShortName(author) : ''),
Não usamos explicitamente o tipo `Ref<User>` sempre preferimos usar o union `User | string | undefined`.

2023-05-03 02:51 UTC, augustoicaro commented on src/app/pages/invoices/invoices.component.ts
> +  loadInvoiceTable(): void {
Cadê a quebra de linha entre as funções?

2023-05-04 21:25 UTC, Elygledson commented on src/app/pages/invoices/invoices.component.ts
> +        valuePrepareFunction: (author: Ref<User>) => (author ? this.userService.idToShortName(author) : ''),
Feito!

2023-05-04 21:25 UTC, Elygledson commented on src/app/pages/invoices/invoices.component.ts
> +  loadInvoiceTable(): void {
Feito!

2023-05-20 18:14 UTC, augustoicaro commented
Feito em ninc-2069

2023-05-20 18:14 UTC, closed without merging