[NINC-2028][NINC-2078] Review team component
ninc-management/plataforma pull request #459
Opened 2023-04-17 23:31 UTC by Elygledson

2023-05-03 02:55 UTC, augustoicaro requested changes
Dá uma olhada nesses pontos que levantei aqui.

2023-05-03 02:55 UTC, augustoicaro commented on src/app/pages/teams/teams.component.ts
> +            .join(', ');
Falta as outras 2 funções. A de find e a de sort

2023-05-03 02:55 UTC, augustoicaro commented on src/app/pages/teams/teams.component.ts
> +        valuePrepareFunction: (leader: User) => (leader ? this.userService.idToUser(leader).fullName : ''),
Falta as outras 2 funções. A de find e a de sort

2023-05-10 22:47 UTC, Elygledson commented on src/app/pages/teams/teams.component.ts
> +            .join(', ');
Augusto eu não entendi muito bem. Eu coloquei o sort e ai deixou ordenado. A função filter não precisou porque já está funcionando corretamente. Eu testei aqui. So a leader que precisou porque estava errado

2023-05-20 19:05 UTC, augustoicaro commented on src/app/pages/teams/teams.component.ts
> +            .join(', ');
Essa resposta foi muito boa, Acho que não fui muito claro na funções que falei. Estou falando das funções da tabela para sort e filter que são respectivamente `compareFunction` e `filterFunction`. Toda que que usamos o `valuePrepareFunction` em um objeto também temos que definir `compareFunction` e `filterFunction`, ou a tabela não funcionará corretamente.

2023-05-20 19:20 UTC, augustoicaro approved these changes

2023-05-20 19:31 UTC, merged