[NINC-2048][NINC-2132] Treat budgets in analysis and value of budgets
ninc-management/plataforma pull request #484
Opened 2023-06-29 23:24 UTC by Elygledson

2023-07-19 00:55 UTC, augustoicaro requested changes
A conta está certa, só o nome da variável que ficou estranho.

2023-07-19 00:55 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                  const monthsUnderReview = monthInvoice.invoice.statusHistory.find(
Esse nome da variável não reflete o que você está pegando no find. O objeto é um `StatusEditionHistoryItem`, qual a relação com `monthsUnderReview`?

2023-07-19 20:13 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                  const monthsUnderReview = monthInvoice.invoice.statusHistory.find(
feito!

2024-02-02 23:19 UTC, augustoicaro approved these changes

2024-02-02 23:36 UTC, merged