[NINC-2048][NINC-2133] Implement Nº Contracts in progress
ninc-management/plataforma pull request #487
Opened 2023-07-05 22:58 UTC by Elygledson

2023-07-05 23:03 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
>                    )
Esta condição me chamou a atenção pois toda vez os contratos com status RECEBER e EM ANDAMENTO vão entrar porém eu vi que só uma é atualizada.

export interface TeamData {
  support_organization: string;
  support_personal: string;
  oe_gross: string;
  oe_net: string;
  oe_nf: string;
  oe_organization: string;
  op: string;
  expenses: string;
  expenses_total: string;
  net_balance: string;
  sent_invoices: number;
  sent_invoices_value: string;
  concluded_invoices: number;
  concluded_invoices_value: string;
  convertion_time: number;
  balance: string;
  not_paid: string;
  ongoing_contracts: number;
  ongoing_oe: number;
  ongoing_oe_value: string;
  ongoing_invoice: number;
  ongoing_invoice_value: string;
}
@augustoicaro qual é a propriedade que posso usar para incrementar aqui?

2023-07-19 00:49 UTC, augustoicaro requested changes
Dá uma olhada por favor nos pontos que levantei aqui

2023-07-19 00:49 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                  const monthsInProgress = monthContract.contract.statusHistory.find(
Esse nome da variável não reflete o que você está pegando no find. O objeto é um `StatusEditionHistoryItem`, qual a relação com `monthsInProgress`

2023-07-19 00:49 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
>                    )
> Esta condição me chamou a atenção pois toda vez os contratos com status RECEBER e EM ANDAMENTO vão entrar porém eu vi que só uma é atualizada.

Como assim somente uma é atualizada?

> @augustoicaro qual é a propriedade que posso usar para incrementar aqui?

A que tiver para a métrica. Só olhar no arquivo de referência

2023-07-19 00:49 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                    (item) => item.status === CONTRACT_STATOOS.EM_ANDAMENTO
Esse find aqui tem vários pontos não cobertos. Primeiramente o find vai achar somente a primeira instância de um `StatusEditionHistoryItem` que tem o status  `CONTRACT_STATOOS.EM_ANDAMENTO`. O problema disso é que os contratatos tem vários itens de `StatusEditionHistoryItem` com status `CONTRACT_STATOOS.EM_ANDAMENTO` e `CONTRACT_STATOOS.A_RECEBER`. Aí a lógica aqui é tratar todos esses intervalos. Então de todos os possíveis intervalos você só está tratando apenas 1 para o caso `CONTRACT_STATOOS.EM_ANDAMENTO`

2023-10-24 22:43 UTC, augustoicaro approved these changes

2024-02-02 23:33 UTC, merged