[NINC-1174][NINC-2135]   Add cumulative metric
ninc-management/plataforma pull request #488
Opened 2023-07-11 23:45 UTC by Elygledson

2023-07-19 00:39 UTC, augustoicaro requested changes
Altera o branch base dessa aqui que tem commits a mais que vinheram de outros branches mais recentes

2023-07-19 00:39 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                            const endDate = endOfMonth(setMonth(new Date(year, month), month));
Me explica a necessidade de fazer um `setMonth` aqui nessa conta por favor

2023-07-19 00:39 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
>      const expenseContribution = this.expensesContributions(contract);
`expensesContributions` também precisa receber um `endDate` como argumento

2023-07-19 00:39 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +            .filter((payment) => payment.paidDate && isSameMonth(payment.paidDate, endDate))
`isSameMonth` não é a lógica que você quer aqui. Aqui eu quero todos as OP até o `endDate`. Ou seja quero filtrar tudo o que foi pago depois do `endDate`.

2023-07-19 00:39 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
>      const expenseContribution = this.expensesContributions(contract);
Você até adicionou o argumento, mas não usou ele corretamente na chamada da função

2023-07-19 00:39 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +          isSameMonth(expense.paidDate, endDate)
`isSameMonth` não é a lógica que você quer aqui. Aqui eu quero todos as OP até o `endDate`. Ou seja quero filtrar tudo o que foi pago depois do `endDate`.

2023-07-19 00:39 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +      .filter((receipt) => receipt.paidDate && isSameMonth(receipt.paidDate, endDate))
`isSameMonth` não é a lógica que você quer aqui. Aqui eu quero todos as OP até o `endDate`. Ou seja quero filtrar tudo o que foi pago depois do `endDate`.

2023-07-19 20:25 UTC, Elygledson commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                            const endDate = endOfMonth(setMonth(new Date(year, month), month));
Feito!

2024-02-19 21:29 UTC, augustoicaro approved these changes

2024-02-29 22:25 UTC, merged