[NINC-1174][NINC-2136] Add cumulative metric 17
ninc-management/plataforma pull request #489
Opened 2023-07-18 23:53 UTC by Elygledson

2023-07-19 00:52 UTC, augustoicaro requested changes

2023-07-19 00:52 UTC, augustoicaro commented on src/app/pages/dashboard/report-menu/annual-report/annual-report.component.ts
> +                            );
Não é isso que deveria ser feito. Me faz um favor para também facilitar a revisão. Coloca na descrição do PR a descrição da métrica. Aí fica mais fácil de revisar.

2023-07-19 23:24 UTC, Elygledson commented
@augustoicaro eu não criei uma outra função no contractService porque já tem funções com nomes semelhantes ao proposito da métrica tipo getBalance ou balance ou notPaidValue

2024-02-19 22:17 UTC, augustoicaro approved these changes

2024-02-29 22:24 UTC, merged