[NINC-1153][NINC-2187] Implement visual feedback to outdated Invoice object
ninc-management/plataforma pull request #536
Opened 2023-10-17 19:44 UTC by pamelams

2023-10-18 23:10 UTC, augustoicaro requested changes

2023-10-18 23:10 UTC, augustoicaro commented on src/app/shared/utils.ts
> +  __v?: number;
Tem que fazer o rebase desse branch. Essas alterações já estão no branch base

2023-10-20 23:55 UTC, pamelams commented
![image](https://github.com/ninc-management/plataforma/assets/32972537/3c1c6e7a-fbca-46ff-8e48-6f127e240443)
![image](https://github.com/ninc-management/plataforma/assets/32972537/9195bf84-51b4-48fb-99a1-8c53a7b0c1f8)

2023-10-24 22:24 UTC, augustoicaro approved these changes

2023-10-24 22:25 UTC, merged